- components/bps-tools/pom.xml
- components/dss-tools/pom.xml
- components/esb-tools/pom.xml
- components/studio-platform/pom.xml
> fixes for Jenkins build failures

- components/bps-tools/features/org.wso2.integrationstudio.bps.feature/pom.xml
- components/dss-tools/features/org.wso2.integrationstudio.dss.feature/pom.xml
- components/esb-tools/features/org.wso2.integrationstudio.esb.feature/pom.xml
> fix name mismatch in feature id and pom id

- distribution/rcp-product/org.wso2.integrationstudio.rcp.product/integrationstudio.product
> Fix About Logo issue

- components/studio-platform/plugins/org.wso2.integrationstudio.eclipse.dashboard/plugin.xml
> Fix help menu contribution issue

- distribution/rcp-product/org.wso2.integrationstudio.rcp.feature/feature.xml
> Rename RCP Feature lebel name

- components/bps-tools/features/org.wso2.integrationstudio.bps.feature/feature.xml
- components/bps-tools/plugins/pom.xml
- components/dss-tools/features/org.wso2.integrationstudio.dss.feature/feature.xml
- components/dss-tools/plugins/pom.xml
- components/esb-tools/plugins/pom.xml
- components/studio-platform/plugins/pom.xml
- components/studio-platform/pom.xml
- components/studio-platform/repository/main/pom.xml
- distribution/rcp-product/org.wso2.integrationstudio.rcp.product/integrationstudio.product
> Add timestamp suffix for studio-platform plugins and features
> fix updater tool issue

- components/studio-platform/plugins/org.wso2.integrationstudio.eclipse.templates.dashboard/src/org/wso2/integrationstudio/eclipse/templates/dashboard/handlers/FeedbackViewerHandler.java
> update report issue URL

- components/studio-platform/plugins/org.wso2.integrationstudio.eclipse.platform.ui/plugin.xml
> remove older update preference

- components/studio-platform/plugins/org.wso2.integrationstudio.eclipse.updater/src/org/wso2/integrationstudio/eclipse/updater/handler/RunUpdaterRootJob.java
> notification tool URL changes

- bash.sh
- components/studio-platform/plugins/org.wso2.integrationstudio.updater/src/org/wso2/integrationstudio/updater/handler/RunUpdaterRootJob.java
- components/studio-platform/plugins/org.wso2.integrationstudio.updater/src/org/wso2/integrationstudio/updater/handler/UpdateNotificationPopUp.java
- distribution/rcp-product/org.wso2.integrationstudio.rcp.product/integrationstudio.product
> Fix runtime issues of updater tool

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/presentation/EEFPropertyViewUtil.java
> Remove word eclipse from the plugin's package paths

- components/studio-platform/plugins/org.wso2.integrationstudio.templates.dashboard/src/org/wso2/integrationstudio/templates/dashboard/web/function/server/JSEmbeddedFunctions.java
> $subject
Fixes https://github.com/wso2/integration-studio/issues/35
> point new github rrepository

- components/studio-platform/plugins/org.wso2.integrationstudio.updater/src/org/wso2/integrationstudio/updater/handler/RunUpdaterRootJob.java
- distribution/rcp-product/org.wso2.integrationstudio.rcp.product/integrationstudio.product
> Change updater P2 repository URL

- gh-docs/developer-guide/integration-studio-catalogue.md
> update developer-guide with new model

- gh-docs/developer-guide/integration-studio-catalogue.md
> Update developer-guide doc

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/custom/deserializer/EnrichMediatorDeserializer.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/custom/deserializer/EnrichMediatorExtFactory.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/parts/forms/EnrichMediatorPropertiesEditionPartForm.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.persistence/src/org/wso2/integrationstudio/gmf/esb/internal/persistence/EnrichMediatorTransformer.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb/model/esb.ecore
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb/model/esb.genmodel
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb/src/org/wso2/integrationstudio/gmf/esb/EnrichTargetType.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb/src/org/wso2/integrationstudio/gmf/esb/impl/EsbPackageImpl.java
> Add key type to the enrich mediator
Related to wso2-synapse/pull/1633
> Add enrich mediator 'key' type

- components/esb-tools/plugins/org.wso2.integrationstudio.visualdatamapper.diagram/src/org/wso2/integrationstudio/datamapper/diagram/tree/generator/SchemaTransformer.java
Porting https://github.com/wso2/integration-studio/pull/49 to update 7.2.0
> fixed xsd reading issue

- components/esb-tools/plugins/org.wso2.integrationstudio.visualdatamapper.diagram/src/org/wso2/integrationstudio/datamapper/diagram/tree/generator/SchemaTransformer.java
Fixing the issue of loading XSD file with a multilevel array in the Data mapper mediator design view.
Related issue: https://github.com/wso2/integration-studio/issues/50
> Fixing XSD reading issue in Data mapper mediator

- components/dss-tools/plugins/org.wso2.integrationstudio.artifact.datasourceproject/META-INF/MANIFEST.MF
- components/dss-tools/plugins/org.wso2.integrationstudio.artifact.datasourceproject/plugin.xml
- components/dss-tools/plugins/org.wso2.integrationstudio.artifact.datasourceproject/src/org/wso2/integrationstudio/artifact/datasourceProject/capp/refactor/DataSourceDeleteParticipant.java
- components/dss-tools/plugins/org.wso2.integrationstudio.artifact.datasourceproject/src/org/wso2/integrationstudio/artifact/datasourceProject/capp/refactor/MavenConfigurationFileDeleteChange.java
- components/dss-tools/plugins/org.wso2.integrationstudio.artifact.datasourceproject/src/org/wso2/integrationstudio/artifact/datasourceProject/refactor/DataSourceDeleteParticipant.java
- components/dss-tools/plugins/org.wso2.integrationstudio.artifact.datasourceproject/src/org/wso2/integrationstudio/artifact/datasourceProject/refactor/DataSourceMetaDataFileDeleteChange.java
- components/dss-tools/plugins/org.wso2.integrationstudio.artifact.datasourceproject/src/org/wso2/integrationstudio/artifact/datasourceProject/utils/DataSourceProjectConstants.java
- components/dss-tools/plugins/org.wso2.integrationstudio.artifact.datasourceproject/src/org/wso2/integrationstudio/artifact/datasourceProject/utils/datasourceprojectconstants.properties
> $subject. 
Fixes: https://github.com/wso2/integration-studio/issues/54
> Add delete participant for datasource artifacts

- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.connector/src/org/wso2/integrationstudio/artifact/connector/ui/wizard/ConnectorCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.endpoint/src/org/wso2/integrationstudio/artifact/endpoint/ui/wizard/EndpointProjectCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.inboundendpoint/src/org/wso2/integrationstudio/artifact/inboundendpoint/ui/wizard/InboundEndpointProjectCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.localentry/src/org/wso2/integrationstudio/artifact/localentry/ui/wizard/LocalEntryProjectCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.messageprocessor/src/org/wso2/integrationstudio/artifact/messageprocessor/wizard/MessageProcessorCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.messagestore/src/org/wso2/integrationstudio/artifact/messagestore/ui/wizard/MessageStoreCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.proxyservice/src/org/wso2/integrationstudio/artifact/proxyservice/ui/wizard/ProxyServiceProjectCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.sequence/src/org/wso2/integrationstudio/artifact/sequence/ui/wizard/SequenceProjectCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/ui/wizard/SynapseAPICreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.task/src/org/wso2/integrationstudio/artifact/task/ui/wizard/TaskCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.template.sequence/src/org/wso2/integrationstudio/artifact/template/wizards/TemplateProjectCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.project/src/org/wso2/integrationstudio/esb/project/utils/ESBProjectUtils.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/edit/parts/CallTemplateMediatorEditPart.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/edit/parts/NamedEndpointEditPart.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/edit/parts/SequenceEditPart.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/presentation/EEFPropertyViewUtil.java
> Fix mvn build issue with java 11 for esb projects
> Fix java 11 build issues with ESB project pom file

- gh-docs/developer-guide/integration-studio-catalogue.md
> update new eclipse formatter and cleanup code styles

- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/src/org/wso2/integrationstudio/esb/dashboard/templates/maven/wizard/CommonTemplateProjectCreationWizard.java
- components/studio-platform/plugins/org.wso2.integrationstudio.docker.distribution/src/org/wso2/integrationstudio/docker/distribution/ui/wizard/ContainerProjectCreationWizard.java
> $subject
Fixes: https://github.com/wso2/integration-studio/issues/125
> upgrade mi-congif-mapper version

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/custom/deserializer/InboundEndpointDeserializer.java
> $subject
Fixes: https://github.com/wso2/integration-studio/issues/568
> Fix transport.vfs.Locking parameter issue in File inbound endpoint

- components/studio-platform/plugins/org.wso2.integrationstudio.docker.distribution/src/org/wso2/integrationstudio/docker/distribution/action/DockerRunMavenAction.java
- components/studio-platform/plugins/org.wso2.integrationstudio.docker.distribution/src/org/wso2/integrationstudio/docker/distribution/editor/DistProjectEditorPage.java
> $subject
Fixes: https://github.com/wso2/integration-studio/issues/575
> Fix custom docker registry URLs for images issue

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.persistence/src/org/wso2/integrationstudio/gmf/esb/internal/persistence/JsonTransformMediatorTransformer.java
> Fix: https://github.com/wso2/integration-studio/issues/578
> fix jsonTransformer serialisation issue in sequences

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.persistence/src/org/wso2/integrationstudio/gmf/esb/internal/persistence/JsonTransformMediatorTransformer.java
> Fix: https://github.com/wso2/integration-studio/issues/578
> fix jsonTransformer serialization issue in sequences

- components/studio-platform/plugins/org.wso2.integrationstudio.carbonserver.base/src/org/wso2/integrationstudio/carbonserver/base/impl/CarbonServerBehaviour.java
- pom.xml
> $subject
Fixes: https://github.com/wso2/integration-studio/issues/70
> Remove server port check when starting external servers update

- pom.xml
> Add profile to build all the components

- gh-docs/developer-guide/integration-studio-catalogue.md
> Update integration studio catalogue

- gh-docs/developer-guide/integration-studio-catalogue.md
> update developer-guide release section

- components/esb-tools/plugins/org.wso2.integrationstudio.esb.form.editors/src/org/wso2/integrationstudio/esb/form/editors/mockservice/MockServiceFormPage.java
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.form.editors/src/org/wso2/integrationstudio/esb/form/editors/mockservice/MockServiceFormToSourceTransformer.java
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.synapse.unit.test/src/org/wso2/integrationstudio/esb/synapse/unit/test/wizard/mockservice/MockServiceDetailPage.java
> $subject
Fixes: https://github.com/wso2/integration-studio/issues/597
> add dynamic endpoint support for mock services

- components/esb-tools/plugins/org.wso2.integrationstudio.esb.project/src/org/wso2/integrationstudio/esb/project/ui/wizard/ESBSolutionProjectCreationWizard.java
- components/studio-platform/plugins/org.wso2.integrationstudio.docker.distribution/src/org/wso2/integrationstudio/docker/distribution/ui/wizard/DockerProjectCreationWizard.java
- components/studio-platform/plugins/org.wso2.integrationstudio.docker.distribution/src/org/wso2/integrationstudio/docker/distribution/ui/wizard/KubernetesProjectCreationWizard.java
- components/studio-platform/plugins/org.wso2.integrationstudio.maven.multi.module/src/org/wso2/integrationstudio/maven/multi/module/editor/DistProjectEditorPage.java
- components/studio-platform/plugins/org.wso2.integrationstudio.maven.multi.module/src/org/wso2/integrationstudio/maven/multi/module/handlers/MavenParentProjectList.java
- components/studio-platform/plugins/org.wso2.integrationstudio.maven.multi.module/src/org/wso2/integrationstudio/maven/multi/module/handlers/MavenPropertyTester.java
- components/studio-platform/plugins/org.wso2.integrationstudio.maven.multi.module/src/org/wso2/integrationstudio/maven/multi/module/handlers/MvnMultiModuleModel.java
- components/studio-platform/plugins/org.wso2.integrationstudio.maven.multi.module/src/org/wso2/integrationstudio/maven/multi/module/handlers/MvnMultiModuleWizard.java
- components/studio-platform/plugins/org.wso2.integrationstudio.platform.core/src/org/wso2/integrationstudio/platform/core/project/model/ProjectDataModel.java
- components/studio-platform/plugins/org.wso2.integrationstudio.platform.ui/src/org/wso2/integrationstudio/platform/ui/wizard/AbstractWSO2ProjectCreationWizard.java
- components/studio-platform/plugins/org.wso2.integrationstudio.platform.ui/src/org/wso2/integrationstudio/platform/ui/wizard/pages/MavenDetailsPage.java
> $subject
Fixes: https://github.com/wso2/integration-studio/issues/602
> Add parent maven details inside children pom by default

- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/src/org/wso2/integrationstudio/esb/dashboard/templates/maven/wizard/TemplateCreationUtil.java
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.project/src/org/wso2/integrationstudio/esb/project/ui/wizard/ESBProjectWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.synapse.unit.test/src/org/wso2/integrationstudio/esb/synapse/unit/test/component/DependencyTree.java
> $subject
Fixes: https://github.com/wso2/integration-studio/issues/606
> Fix unit test suite path issue in windows

- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.connector/src/org/wso2/integrationstudio/artifact/connector/ui/wizard/ConnectorCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.endpoint/src/org/wso2/integrationstudio/artifact/endpoint/ui/wizard/EndpointProjectCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.inboundendpoint/src/org/wso2/integrationstudio/artifact/inboundendpoint/ui/wizard/InboundEndpointProjectCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.localentry/src/org/wso2/integrationstudio/artifact/localentry/ui/wizard/LocalEntryProjectCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.messageprocessor/src/org/wso2/integrationstudio/artifact/messageprocessor/wizard/MessageProcessorCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.messagestore/src/org/wso2/integrationstudio/artifact/messagestore/ui/wizard/MessageStoreCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.proxyservice/src/org/wso2/integrationstudio/artifact/proxyservice/ui/wizard/ProxyServiceProjectCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.sequence/src/org/wso2/integrationstudio/artifact/sequence/ui/wizard/SequenceProjectCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/ui/wizard/SynapseAPICreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.task/src/org/wso2/integrationstudio/artifact/task/ui/wizard/TaskCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.template.sequence/src/org/wso2/integrationstudio/artifact/template/wizards/TemplateProjectCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.project/src/org/wso2/integrationstudio/esb/project/utils/ESBProjectUtils.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/edit/parts/CallTemplateMediatorEditPart.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/edit/parts/NamedEndpointEditPart.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/edit/parts/SequenceEditPart.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/presentation/EEFPropertyViewUtil.java
- components/studio-platform/plugins/org.wso2.integrationstudio.maven/src/main/java/org/wso2/integrationstudio/maven/util/MavenUtils.java
- components/studio-platform/plugins/org.wso2.integrationstudio.maven/src/main/java/org/wso2/integrationstudio/maven/util/WSO2MavenPluginVersions.java
> Fix JDK issue for projects and artifacts

- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.connector/src/org/wso2/integrationstudio/artifact/connector/ui/wizard/ConnectorCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.endpoint/src/org/wso2/integrationstudio/artifact/endpoint/ui/wizard/EndpointProjectCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.inboundendpoint/src/org/wso2/integrationstudio/artifact/inboundendpoint/ui/wizard/InboundEndpointProjectCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.localentry/src/org/wso2/integrationstudio/artifact/localentry/ui/wizard/LocalEntryProjectCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.messageprocessor/src/org/wso2/integrationstudio/artifact/messageprocessor/wizard/MessageProcessorCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.messagestore/src/org/wso2/integrationstudio/artifact/messagestore/ui/wizard/MessageStoreCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.proxyservice/src/org/wso2/integrationstudio/artifact/proxyservice/ui/wizard/ProxyServiceProjectCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.sequence/src/org/wso2/integrationstudio/artifact/sequence/ui/wizard/SequenceProjectCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/ui/wizard/SynapseAPICreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.task/src/org/wso2/integrationstudio/artifact/task/ui/wizard/TaskCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.template.sequence/src/org/wso2/integrationstudio/artifact/template/wizards/TemplateProjectCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.project/src/org/wso2/integrationstudio/esb/project/utils/ESBProjectUtils.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/edit/parts/CallTemplateMediatorEditPart.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/edit/parts/NamedEndpointEditPart.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/edit/parts/SequenceEditPart.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/presentation/EEFPropertyViewUtil.java
- components/studio-platform/plugins/org.wso2.integrationstudio.maven/src/main/java/org/wso2/integrationstudio/maven/util/MavenUtils.java
- components/studio-platform/plugins/org.wso2.integrationstudio.maven/src/main/java/org/wso2/integrationstudio/maven/util/WSO2MavenPluginVersions.java
> Fix JDK issue for projects and artifacts 

- components/server-tools/plugins/org.wso2.integrationstudio.carbonserver44microei40/src/org/wso2/integrationstudio/carbonserver44microei40/handlers/PlatformEarlyStartUpHandler.java
> fix server plugin path issue

- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/util/MetadataUtils.java
- components/studio-platform/plugins/org.wso2.integrationstudio.distribution.project/src/org/wso2/integrationstudio/distribution/project/export/CarExportHandler.java
> Change metadata yaml
Change CAPP export to include metadata.xml
> Change metadata yaml

- components/studio-platform/plugins/org.wso2.integrationstudio.distribution.project/src/org/wso2/integrationstudio/distribution/project/ui/wizard/DistributionProjectExportWizardPage.java
> refactor CApp exporter wizard

- components/esb-tools/plugins/org.wso2.integrationstudio.esb.form.editors/src/org/wso2/integrationstudio/esb/form/editors/mockservice/MockServiceFormPage.java
> Fix issue in mock service editor

- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/ui/wizard/SynapseAPICreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.project/src/org/wso2/integrationstudio/esb/project/refactoring/delete/ESBArtifactMetaDataDeleteParticipant.java
- components/studio-platform/plugins/org.wso2.integrationstudio.distribution.project/src/org/wso2/integrationstudio/distribution/project/editor/DistProjectEditorPage.java
- components/studio-platform/plugins/org.wso2.integrationstudio.distribution.project/src/org/wso2/integrationstudio/distribution/project/export/CarExportHandler.java
- components/studio-platform/plugins/org.wso2.integrationstudio.distribution.project/src/org/wso2/integrationstudio/distribution/project/ui/wizard/DistributionProjectExportWizardPage.java
>Remove metadata functionalities when the project type is old.
Related to wso2/integration-studio/issues/67
> Add backwards compatibility fixes

- components/dss-tools/plugins/org.wso2.integrationstudio.ds.editor/DSSEditor/assets/js/constants.js
- components/dss-tools/plugins/org.wso2.integrationstudio.ds.editor/DSSEditor/assets/js/data-handler.js
- components/dss-tools/plugins/org.wso2.integrationstudio.ds.editor/DSSEditor/assets/js/datasources-util.js
- components/dss-tools/plugins/org.wso2.integrationstudio.ds.editor/DSSEditor/assets/js/ds-validation.js
- components/dss-tools/plugins/org.wso2.integrationstudio.ds.editor/DSSEditor/index.html
> Fix: https://github.com/wso2/integration-studio/issues/632
> Add Cassandra data source support for Integration Studio

- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/util/MetadataUtils.java
> Append API version when its URL based version strategy.
> Fix api version issue in metadata files.

- components/dss-tools/plugins/org.wso2.integrationstudio.ds.editor/DSSEditor/assets/js/datasources-util.js
> Fix Cassandra datasource loading issue

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/part/EsbMultiPageEditor.java
> $subject. Handling file not found exceptions
> Fix issue in ESBMultiPageEditor

- components/server-tools/plugins/org.wso2.integrationstudio.carbonserver44microei40/resources/server/deployment.toml
- components/studio-platform/plugins/org.wso2.integrationstudio.docker.distribution/resources/deployment.toml
> Add service-catalog toml configuration.
> Add service-catalog toml configuration.

- components/server-tools/plugins/org.wso2.integrationstudio.carbonserver44microei40/src/org/wso2/integrationstudio/carbonserver44microei40/handlers/PlatformEarlyStartUpHandler.java
> Fix runtime backup issue

- components/esb-tools/plugins/org.wso2.integrationstudio.visualdatamapper.diagram/src/org/wso2/integrationstudio/datamapper/diagram/custom/action/AddNewArrayAction.java
- components/esb-tools/plugins/org.wso2.integrationstudio.visualdatamapper.diagram/src/org/wso2/integrationstudio/datamapper/diagram/custom/action/AddNewAttributeAction.java
- components/esb-tools/plugins/org.wso2.integrationstudio.visualdatamapper.diagram/src/org/wso2/integrationstudio/datamapper/diagram/custom/action/AddNewFieldAction.java
- components/esb-tools/plugins/org.wso2.integrationstudio.visualdatamapper.diagram/src/org/wso2/integrationstudio/datamapper/diagram/custom/action/AddNewObjectAction.java
> $subject
Fixes: https://github.com/wso2/integration-studio/issues/642
> Fix issue while adding any new field in datamapper

- components/esb-tools/plugins/org.wso2.integrationstudio.visualdatamapper.diagram/src/org/wso2/integrationstudio/datamapper/diagram/custom/action/AddNewArrayAction.java
- components/esb-tools/plugins/org.wso2.integrationstudio.visualdatamapper.diagram/src/org/wso2/integrationstudio/datamapper/diagram/custom/action/AddNewAttributeAction.java
- components/esb-tools/plugins/org.wso2.integrationstudio.visualdatamapper.diagram/src/org/wso2/integrationstudio/datamapper/diagram/custom/action/AddNewFieldAction.java
- components/esb-tools/plugins/org.wso2.integrationstudio.visualdatamapper.diagram/src/org/wso2/integrationstudio/datamapper/diagram/custom/action/AddNewObjectAction.java
> $subject
Fixes: https://github.com/wso2/integration-studio/issues/642
> Fix issue in datamapper add new elements

- components/studio-platform/plugins/org.wso2.integrationstudio.docker.distribution/src/org/wso2/integrationstudio/docker/distribution/ui/wizard/ContainerProjectCreationWizard.java
> update integration_cr yaml file content

- components/server-tools/plugins/org.wso2.integrationstudio.carbonserver44microei40/resources/server/deployment.toml
- components/studio-platform/plugins/org.wso2.integrationstudio.docker.distribution/resources/deployment.toml
> Change userName to username in toml files
> Change userName in toml files.

- components/esb-tools/plugins/org.wso2.integrationstudio.esb.project/src/org/wso2/integrationstudio/esb/project/ui/wizard/ESBSolutionProjectCreationWizard.java
- components/studio-platform/plugins/org.wso2.integrationstudio.platform.ui/src/org/wso2/integrationstudio/platform/ui/wizard/AbstractWSO2ProjectCreationWizard.java
> $subject
Fixes: https://github.com/wso2/integration-studio/issues/52
> Fix issue when create new integration project in arbitrary directory

- gh-docs/developer-guide/integration-studio-catalogue.md
> [Doc] Update developer guide with server-tools plugin import details

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/presentation/ConnectionParameterRenderer.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/presentation/ConnectionParameterWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/presentation/PropertiesWidgetProvider.java
- components/studio-platform/plugins/org.wso2.integrationstudio.maven.multi.module/plugin.xml
- components/studio-platform/plugins/org.wso2.integrationstudio.maven.multi.module/src/org/wso2/integrationstudio/maven/multi/module/add/other/projects/MMMProjectSelectionWizard.java
- components/studio-platform/plugins/org.wso2.integrationstudio.maven.multi.module/src/org/wso2/integrationstudio/maven/multi/module/add/other/projects/MMMProjectSelectionWizardPage.java
> $subject
Fixes for project move: https://github.com/wso2/integration-studio/issues/26
Fixes for the connector connection: https://github.com/wso2/integration-studio/issues/676
> Fix project import and connector connection wizard issues

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/parts/forms/CallMediatorPropertiesEditionPartForm.java
> Fix call mediator properties not rendered issue

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/parts/forms/CallMediatorPropertiesEditionPartForm.java
> Fix: https://github.com/wso2/integration-studio/issues/678
> Change Call mediator payload inline source payload to text field

- components/studio-platform/plugins/org.wso2.integrationstudio.maven/src/main/java/org/wso2/integrationstudio/maven/util/WSO2MavenPluginVersions.java
>Fix: https://github.com/wso2/integration-studio/issues/658
> Fix JDK 11 build issue for wso2-esb-metadata-plugin

- components/server-tools/plugins/org.wso2.integrationstudio.carbonserver44microei40/src/org/wso2/integrationstudio/carbonserver44microei40/handlers/PlatformEarlyStartUpHandler.java
- components/studio-platform/plugins/org.wso2.integrationstudio.carbonserver44microei/src/org/wso2/integrationstudio/carbonserver44microei/handlers/PlatformEarlyStartUpHandler.java
- components/studio-platform/plugins/org.wso2.integrationstudio.carbonserver44microei11/src/org/wso2/integrationstudio/carbonserver44microei11/handlers/PlatformEarlyStartUpHandler.java
- components/studio-platform/plugins/org.wso2.integrationstudio.carbonserver44microei12/src/org/wso2/integrationstudio/carbonserver44microei12/handlers/PlatformEarlyStartUpHandler.java
- components/studio-platform/plugins/org.wso2.integrationstudio.docker.distribution/plugin.xml
- components/studio-platform/plugins/org.wso2.integrationstudio.docker.distribution/src/org/wso2/integrationstudio/docker/distribution/action/DockerRunMavenAction.java
- components/studio-platform/plugins/org.wso2.integrationstudio.docker.distribution/src/org/wso2/integrationstudio/docker/distribution/editor/DistProjectEditorPage.java
- components/studio-platform/plugins/org.wso2.integrationstudio.docker.distribution/src/org/wso2/integrationstudio/docker/distribution/editor/DockerHubLoginPage.java
> Fixes for:
- https://github.com/wso2/integration-studio/issues/682
- https://github.com/wso2/integration-studio/issues/667
- https://github.com/wso2/integration-studio/issues/663
> Fix issues in alpha release 

- components/server-tools/plugins/org.wso2.integrationstudio.carbonserver44microei40/src/org/wso2/integrationstudio/carbonserver44microei40/handlers/PlatformEarlyStartUpHandler.java
> Fix: https://github.com/wso2/integration-studio/issues/681
> Fix file permission issue for micro-integrator.sh file

- components/studio-platform/plugins/org.wso2.integrationstudio.docker.distribution/src/org/wso2/integrationstudio/docker/distribution/ui/wizard/ContainerProjectCreationWizard.java
- components/studio-platform/plugins/org.wso2.integrationstudio.docker.distribution/src/org/wso2/integrationstudio/docker/distribution/utils/DockerProjectConstants.java
- components/studio-platform/plugins/org.wso2.integrationstudio.docker.distribution/src/org/wso2/integrationstudio/docker/distribution/utils/dockerprojectconstants.properties
> $subject
Fix: https://github.com/wso2/integration-studio/issues/697
> Fix issue while building docker image

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/custom/deserializer/CallMediatorDeserializer.java
> Fix: https://github.com/wso2/integration-studio/issues/679
> Fix call mediator deserialisation issue

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/presentation/EEFNameSpacedPropertyEditorDialog.java
> Fix: https://github.com/wso2/integration-studio/issues/674
> fix Namespace editor help blank issue

- components/dss-tools/plugins/org.wso2.integrationstudio.ds.editor/DSSEditor/assets/css/input.css
- components/dss-tools/plugins/org.wso2.integrationstudio.ds.editor/DSSEditor/index.html
Add mandatory indication to mandatory fields in DSS
Fixes https://github.com/wso2/integration-studio/issues/662
> Add mandatory indication to mandatory fields in DSS

- components/esb-tools/plugins/org.wso2.integrationstudio.apim.endpoint.central/src/org/wso2/integrationstudio/apim/endpoint/central/handler/EndpointCentralServletRequestHandler.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.endpoint/src/org/wso2/integrationstudio/artifact/endpoint/refactor/RefactorUtils.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.endpoint/src/org/wso2/integrationstudio/artifact/endpoint/ui/wizard/EndpointProjectCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.inboundendpoint/src/org/wso2/integrationstudio/artifact/inboundendpoint/ui/wizard/InboundEndpointProjectCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.localentry/src/org/wso2/integrationstudio/artifact/localentry/ui/wizard/LocalEntryProjectCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.messageprocessor/src/org/wso2/integrationstudio/artifact/messageprocessor/wizard/MessageProcessorCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.messagestore/src/org/wso2/integrationstudio/artifact/messagestore/ui/wizard/MessageStoreCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.proxyservice/src/org/wso2/integrationstudio/artifact/proxyservice/ui/wizard/ProxyServiceProjectCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.sequence/src/org/wso2/integrationstudio/artifact/sequence/ui/wizard/SequenceProjectCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/ui/wizard/SynapseAPICreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.task/src/org/wso2/integrationstudio/artifact/task/ui/wizard/TaskCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.template.sequence/src/org/wso2/integrationstudio/artifact/template/wizards/TemplateProjectCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.project/src/org/wso2/integrationstudio/esb/project/FileModificationManager.java
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.project/src/org/wso2/integrationstudio/esb/project/utils/RefactorUtils.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/presentation/ConnectionParameterWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/presentation/EEFPropertyViewUtil.java
- components/studio-platform/plugins/org.wso2.integrationstudio.artifact.registry/src/org/wso2/integrationstudio/artifact/registry/ui/wizard/RegistryResourceCreationWizard.java
> $subject
Fix: https://github.com/wso2/integration-studio/issues/689
> Remove snapshot suffix from esb artifact version

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/part/EsbMultiPageEditor.java
> Update the old swagger with the new swagger when it's checked.
Fixes wso2/integration-studio/issues/661
> Change dirty check logic in swagger editor

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/presentation/ConnectorParameterRenderer.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/presentation/PropertiesWidgetProvider.java
Fixing connector properties view default value not showing issue.
Fixes https://github.com/wso2/integration-studio/issues/76
> Fixing connector properties view default value not showing issue

- components/server-tools/plugins/org.wso2.integrationstudio.carbonserver44microei40/resources/server/deployment.toml
- components/studio-platform/plugins/org.wso2.integrationstudio.distribution.project/src/org/wso2/integrationstudio/distribution/project/ui/wizard/DistributionProjectExportWizardPage.java
- components/studio-platform/plugins/org.wso2.integrationstudio.docker.distribution/resources/deployment.toml
> Add metadata for APIs in CAPP export wizard.
Add service-catalog changes for deployment.toml files.
Fixes wso2/integration-studio/issues/705
> Add metadata for APIs in CAPP export wizard.

- components/server-tools/plugins/org.wso2.integrationstudio.carbonserver44microei40/src/org/wso2/integrationstudio/carbonserver44microei40/register/product/servers/MicroIntegratorInstance.java
> enable embedded server config settings

- components/studio-platform/plugins/org.wso2.integrationstudio.carbonserver44ei/resources/server.properties
> Fix: https://github.com/wso2/integration-studio/issues/33
> Fix port offset issue with EI servers

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/presentation/ConnectionParameterWizard.java
Adding confirmation dialog box before replacing an existing connection in Connection Parameter Wizard
Fixes https://github.com/wso2/integration-studio/issues/627
> Handling already existing connection in Connection Parameter Wizard

- components/server-tools/plugins/org.wso2.integrationstudio.carbonserver44microei40/src/org/wso2/integrationstudio/carbonserver44microei40/monitor/CarbonServerListener.java
- components/server-tools/plugins/org.wso2.integrationstudio.carbonserver44microei40/src/org/wso2/integrationstudio/carbonserver44microei40/monitor/EmbeddedServerConfigurationUtil.java
- components/server-tools/plugins/org.wso2.integrationstudio.carbonserver44microei40/src/org/wso2/integrationstudio/carbonserver44microei40/monitoring/dashboard/MonitoringDashboard.java
- components/server-tools/plugins/org.wso2.integrationstudio.carbonserver44microei40/src/org/wso2/integrationstudio/carbonserver44microei40/monitoring/dashboard/util/MonitoringDashboardUtil.java
- components/server-tools/plugins/org.wso2.integrationstudio.carbonserver44microei40/src/org/wso2/integrationstudio/carbonserver44microei40/register/product/servers/MicroIntegratorInstance.java
> $subject
Fix: https://github.com/wso2/integration-studio/issues/715
> Fix embedded server stopping action issue

- distribution/rcp-product/org.wso2.integrationstudio.rcp.product/pom.xml
- pom.xml
> Temp location of dashboard dist

- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.localentry/src/org/wso2/integrationstudio/artifact/localentry/ui/wizard/LocalEntryProjectCreationWizard.java
> $subject
Fixes: https://github.com/wso2/integration-studio/issues/687
> Fix issue when deleting imported local entry

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/presentation/ConnectionParameterWizard.java
> $subject
Fixes: https://github.com/wso2/integration-studio/issues/675
> Fix: removing a local entry does not update artifact.xml when edit it

- components/studio-platform/plugins/org.wso2.integrationstudio.distribution.project/src/org/wso2/integrationstudio/distribution/project/configure/embeddedserver/EmbeddedServerConfigWizard.java
> Fix OS type detection issue when configuring securevault.
Fixes wso2/integration-studio/issues/57
> Fix OS type detection issue.

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/presentation/ConnectionParameterRenderer.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/presentation/ConnectionParameterWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/presentation/ConnectionParameterWizardPage.java
Preventing from creating a connection when mandatory fields are not filled.
Fixes https://github.com/wso2/integration-studio/issues/629
> Checking mandatory fields before creating connection

- components/esb-tools/plugins/org.wso2.integrationstudio.esb.project/src/org/wso2/integrationstudio/esb/project/ui/wizard/ESBSolutionProjectCreationWizard.java
> $subject
Fixes: https://github.com/wso2/integration-studio/issues/712
> Fix issue: Pure K8s artifacts when creating a new Integration Project

- components/studio-platform/plugins/org.wso2.integrationstudio.docker.distribution/src/org/wso2/integrationstudio/docker/distribution/ui/wizard/DockerNavigatorActionProvider.java
- components/studio-platform/plugins/org.wso2.integrationstudio.platform.ui/src/org/wso2/integrationstudio/platform/ui/wizard/pages/KubernetesDetailsPage.java
> $subject
Fixes: https://github.com/wso2/integration-studio/issues/736
> Fix issues in k8s exporter module

- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/src/org/wso2/integrationstudio/esb/dashboard/templates/maven/wizard/CommonTemplateProjectCreationWizard.java
- components/studio-platform/plugins/org.wso2.integrationstudio.docker.distribution/src/org/wso2/integrationstudio/docker/distribution/ui/wizard/ContainerProjectCreationWizard.java
- components/studio-platform/plugins/org.wso2.integrationstudio.platform.ui/src/org/wso2/integrationstudio/platform/ui/preferences/PreferenceInitializer.java
- components/studio-platform/plugins/org.wso2.integrationstudio.updater/src/org/wso2/integrationstudio/updater/handler/RunUpdaterRootJob.java
- distribution/rcp-product/org.wso2.integrationstudio.rcp.product/integrationstudio.product
- distribution/rcp-product/org.wso2.integrationstudio.rcp.product/pom.xml
- gh-docs/developer-guide/integration-studio-catalogue.md
- pom.xml
> $subject
Fixes: https://github.com/wso2/integration-studio/issues/688
> Convert product-dist.wso2.com host URL protocol as HTTPS

- distribution/rcp-product/org.wso2.integrationstudio.rcp.product/integrationstudio.product
> Fix: https://github.com/wso2/integration-studio/issues/541
> Fix windows character encoding issue

- components/esb-tools/plugins/org.wso2.integrationstudio.esb.project/src/org/wso2/integrationstudio/esb/project/ui/wizard/CloudConnectorImportWizard.java
> $subjecct
Fixes: https://github.com/wso2/integration-studio/issues/48
> Fix wizard finish button focus issue

- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.connector/META-INF/MANIFEST.MF
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.connector/plugin.xml
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.connector/src/org/wso2/integrationstudio/artifact/connector/artifact/ConnectorDeleteParticipant.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.connector/src/org/wso2/integrationstudio/artifact/connector/artifact/ConnectorMetaDataFileDeleteChange.java
> $subject
Fixes: https://github.com/wso2/integration-studio/issues/708
> Add delete participant for connector ZIP

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/parts/forms/AddressEndPointPropertiesEditionPartForm.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/parts/forms/DefaultEndPointPropertiesEditionPartForm.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/parts/forms/NamedEndpointPropertiesEditionPartForm.java
> Fix: https://github.com/wso2/integration-studio/issues/170
> fix Inline option not working issue with inline endpoints

- components/studio-platform/plugins/org.wso2.integrationstudio.distribution.project/src/org/wso2/integrationstudio/distribution/project/editor/DistProjectEditorPage.java
- components/studio-platform/plugins/org.wso2.integrationstudio.distribution.project/src/org/wso2/integrationstudio/distribution/project/ui/wizard/DistributionProjectExportWizardPage.java
> $subject
Fixes: https://github.com/wso2/integration-studio/issues/709
> Fix remove dependency issue in CApp POM

- components/esb-tools/plugins/org.wso2.integrationstudio.esb.cloud/plugin.xml
> Fix: https://github.com/wso2/integration-studio/issues/96
> Remove Deploy to Integration Cloud option from Integration Studio

- components/esb-tools/plugins/org.wso2.integrationstudio.apim.endpoint.central/src/org/wso2/integrationstudio/apim/endpoint/central/client/APIMCTLClient.java
- components/esb-tools/plugins/org.wso2.integrationstudio.apim.project/src/org/wso2/integrationstudio/apim/project/wizard/creation/APIMProjectCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.docker/src/org/wso2/integrationstudio/esb/docker/wizard/ExportAndGenerateDockerImageWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.synapse.unit.test/src/org/wso2/integrationstudio/esb/synapse/unit/test/wizard/runtest/UnitTestConfigurationDetailPage.java
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.synapse.unit.test/src/org/wso2/integrationstudio/esb/synapse/unit/test/wizard/runtest/UnitTestConfigurationWizard.java
- components/server-tools/plugins/org.wso2.integrationstudio.carbonserver44microei40/src/org/wso2/integrationstudio/carbonserver44microei40/handlers/PlatformEarlyStartUpHandler.java
- components/server-tools/plugins/org.wso2.integrationstudio.carbonserver44microei40/src/org/wso2/integrationstudio/carbonserver44microei40/monitoring/dashboard/util/MonitoringDashboardUtil.java
- components/server-tools/plugins/org.wso2.integrationstudio.carbonserver44microei40/src/org/wso2/integrationstudio/carbonserver44microei40/register/product/servers/MicroIntegratorInstance.java
- components/studio-platform/plugins/org.wso2.integrationstudio.carbonserver44microei/src/org/wso2/integrationstudio/carbonserver44microei/register/product/servers/MicroIntegratorInstance.java
- components/studio-platform/plugins/org.wso2.integrationstudio.carbonserver44microei11/src/org/wso2/integrationstudio/carbonserver44microei11/register/product/servers/MicroIntegratorInstance.java
- components/studio-platform/plugins/org.wso2.integrationstudio.carbonserver44microei12/src/org/wso2/integrationstudio/carbonserver44microei12/monitoring/dashboard/util/MonitoringDashboardUtil.java
- components/studio-platform/plugins/org.wso2.integrationstudio.carbonserver44microei12/src/org/wso2/integrationstudio/carbonserver44microei12/register/product/servers/MicroIntegratorInstance.java
- components/studio-platform/plugins/org.wso2.integrationstudio.distribution.project/src/org/wso2/integrationstudio/distribution/project/configure/embeddedserver/EmbeddedServerConfigWizard.java
- components/studio-platform/plugins/org.wso2.integrationstudio.docker.distribution/src/org/wso2/integrationstudio/docker/distribution/action/DockerBuildActionUtil.java
- components/studio-platform/plugins/org.wso2.integrationstudio.docker.distribution/src/org/wso2/integrationstudio/docker/distribution/ui/wizard/ContainerProjectCreationWizard.java
- components/studio-platform/plugins/org.wso2.integrationstudio.templates.dashboard/src/org/wso2/integrationstudio/templates/dashboard/handlers/PlatformEarlyStartUpHandler.java
- components/studio-platform/plugins/org.wso2.integrationstudio.updater/src/org/wso2/integrationstudio/updater/handler/RunUpdaterRootJob.java
> $subject
Fixes: https://github.com/wso2/integration-studio/issues/707
> Fix tooling static name issue on macOS

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/custom/dialogs/ESBDataMapperConfigurationDialog.java
- components/studio-platform/plugins/org.wso2.integrationstudio.platform.ui/src/org/wso2/integrationstudio/platform/ui/wizard/AbstractWSO2ProjectCreationWizard.java
> $subject
Fixes: https://github.com/wso2/integration-studio/issues/133
> Fix registry project created outside when creating datamapper

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/custom/deserializer/InboundEndpointDeserializer.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/model/esb.components
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/plugin.properties
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/components/InboundEndpointParameterPropertiesEditionComponent.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/parts/EsbViewsRepository.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/parts/InboundEndpointParameterPropertiesEditionPart.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/parts/forms/InboundEndpointParameterPropertiesEditionPartForm.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/parts/impl/InboundEndpointParameterPropertiesEditionPartImpl.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src/org/wso2/integrationstudio/gmf/esb/provider/InboundEndpointParameterItemProvider.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.persistence/src/org/wso2/integrationstudio/gmf/esb/internal/persistence/InboundEndpointTransformer.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb/model/esb.ecore
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb/model/esb.genmodel
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb/src/org/wso2/integrationstudio/gmf/esb/EsbPackage.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb/src/org/wso2/integrationstudio/gmf/esb/InboundEndpointParameter.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb/src/org/wso2/integrationstudio/gmf/esb/impl/EsbPackageImpl.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb/src/org/wso2/integrationstudio/gmf/esb/impl/InboundEndpointParameterImpl.java
$subject
Fix https://github.com/wso2/integration-studio/issues/51
> Add registry key value for inbound endpoint parameters

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src/org/wso2/integrationstudio/gmf/esb/provider/InboundEndpointParameterItemProvider.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb/src/org/wso2/integrationstudio/gmf/esb/impl/InboundEndpointParameterImpl.java
> fix dangling issue with inbound endpoint parameter registry key

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src/org/wso2/integrationstudio/gmf/esb/provider/InboundEndpointParameterItemProvider.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb/src/org/wso2/integrationstudio/gmf/esb/impl/InboundEndpointParameterImpl.java
Reverts wso2/integration-studio#762
> Revert "fix dangling issue with inbound endpoint parameter registry key"

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/custom/deserializer/InboundEndpointDeserializer.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/model/esb.components
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/plugin.properties
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/components/InboundEndpointParameterPropertiesEditionComponent.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/parts/EsbViewsRepository.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/parts/InboundEndpointParameterPropertiesEditionPart.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/parts/forms/InboundEndpointParameterPropertiesEditionPartForm.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/parts/impl/InboundEndpointParameterPropertiesEditionPartImpl.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src/org/wso2/integrationstudio/gmf/esb/provider/InboundEndpointParameterItemProvider.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.persistence/src/org/wso2/integrationstudio/gmf/esb/internal/persistence/InboundEndpointTransformer.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb/model/esb.ecore
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb/model/esb.genmodel
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb/src/org/wso2/integrationstudio/gmf/esb/EsbPackage.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb/src/org/wso2/integrationstudio/gmf/esb/InboundEndpointParameter.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb/src/org/wso2/integrationstudio/gmf/esb/impl/EsbPackageImpl.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb/src/org/wso2/integrationstudio/gmf/esb/impl/InboundEndpointParameterImpl.java
Reverts wso2/integration-studio#757
> Revert "Add registry key value for inbound endpoint parameters"

- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.connector/src/org/wso2/integrationstudio/artifact/connector/ui/wizard/ConnectorWizardPage.java
Increasing the button width in the Connector import wizard.
Fix: https://github.com/wso2/integration-studio/issues/166
> Increase button width in the connector import wizard

- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/model/APIArtifactModel.java
> $subject
Fixes: https://github.com/wso2/integration-studio/issues/766
> Fix importing swagger name special character issue

- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.endpoint/src/org/wso2/integrationstudio/artifact/endpoint/ui/wizard/EndpointProjectCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.sequence/src/org/wso2/integrationstudio/artifact/sequence/ui/wizard/SequenceProjectCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.form.editors/src/org/wso2/integrationstudio/esb/form/editors/article/providers/NewResourceTemplateDialog.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/custom/dialogs/ESBDataMapperConfigurationDialog.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/custom/provider/NewResourceTemplateDialog.java
- components/studio-platform/plugins/org.wso2.integrationstudio.artifact.library/src/org/wso2/integrationstudio/artifact/library/ui/wizard/LibraryArtifactCreationWizard.java
- components/studio-platform/plugins/org.wso2.integrationstudio.capp.maven/src/org/wso2/integrationstudio/capp/maven/utils/MavenPomGenPluginUtils.java
- components/studio-platform/plugins/org.wso2.integrationstudio.distribution.project/src/org/wso2/integrationstudio/distribution/project/ui/wizard/DistributionProjectWizard.java
- components/studio-platform/plugins/org.wso2.integrationstudio.general.project/src/org/wso2/integrationstudio/general/project/dialogs/NewResourceTemplateDialog.java
- components/studio-platform/plugins/org.wso2.integrationstudio.maven/src/main/java/org/wso2/integrationstudio/maven/util/MavenUtils.java
> $subject
Fixes: https://github.com/wso2/integration-studio/issues/507
> Update wso2 nexus repo protocol as https

- components/esb-tools/plugins/org.wso2.integrationstudio.esb.form.editors/src/org/wso2/integrationstudio/esb/form/editors/article/providers/RegistryKeyPropertyEditorDialog.java
Fix Resource Key Selection Dialog box spacing issue
fix: https://github.com/wso2/integration-studio/issues/272
> Fix Resource Key Selection Dialog box spacing issue

- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.localentry/src/org/wso2/integrationstudio/artifact/localentry/model/LocalEntryModel.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.localentry/src/org/wso2/integrationstudio/artifact/localentry/ui/wizard/LocalEntryProjectCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.localentry/src/org/wso2/integrationstudio/artifact/localentry/validators/LocalEntryProjectFieldController.java
> $subject
Fixes: https://github.com/wso2/integration-studio/issues/592
> Add text support for local-entry source type

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/part/EsbMultiPageEditor.java
> $subject
Fixes: https://github.com/wso2/integration-studio/issues/767
> Fix swagger page dirty issue

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/part/EsbPaletteFactory.java
> Change DSSMediator name to DataServiceCall

- components/server-tools/plugins/org.wso2.integrationstudio.carbonserver44microei40/src/org/wso2/integrationstudio/carbonserver44microei40/operations/CarbonOperationsManager44ei.java
- components/server-tools/plugins/org.wso2.integrationstudio.carbonserver44microei40/src/org/wso2/integrationstudio/carbonserver44microei40/util/CarbonServer44eiUtils.java
- components/studio-platform/plugins/org.wso2.integrationstudio.carbonserver44microei12/src/org/wso2/integrationstudio/carbonserver44microei12/operations/CarbonOperationsManager44ei.java
- components/studio-platform/plugins/org.wso2.integrationstudio.carbonserver44microei12/src/org/wso2/integrationstudio/carbonserver44microei12/util/CarbonServer44eiUtils.java
> $subject
Fixes: https://github.com/wso2/integration-studio/issues/710
> Fix port offset issue in external MI servers

- components/dss-tools/plugins/org.wso2.integrationstudio.artifact.datasourceproject/src/org/wso2/integrationstudio/artifact/datasourceProject/capp/refactor/DataSourceDeleteParticipant.java
- components/dss-tools/plugins/org.wso2.integrationstudio.ds/META-INF/MANIFEST.MF
- components/dss-tools/plugins/org.wso2.integrationstudio.ds/src/org/wso2/integrationstudio/ds/capp/refactor/DataServiceDeleteParticipant.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.connector/src/org/wso2/integrationstudio/artifact/connector/artifact/ConnectorMetaDataFileDeleteChange.java
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.project/src/org/wso2/integrationstudio/esb/project/refactoring/delete/ESBMetaDataFileDeleteChange.java
> $subject
Fixes: https://github.com/wso2/integration-studio/issues/571
> Fix issue when selected artifacts from composite POM

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/part/EsbDiagramActionBarContributor.java
> Fix: https://github.com/wso2/integration-studio/issues/777
> Fix Delete key not working issue in ESB editor

- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/util/MetadataUtils.java
> Change placeholder names in metadat to match env-variables
Fixes wso2/integration-studio/issues/785
> Change placeholder names in metadata.

- components/dss-tools/plugins/org.wso2.integrationstudio.ds.editor/DSSEditor/assets/js/query-util.js
> $subject
Fixes: https://github.com/wso2/integration-studio/issues/784
> Fix issue in generating DSS input mapping

- components/dss-tools/plugins/org.wso2.integrationstudio.artifact.dataservice/project_wizard.xml
> $subject
Fixes: https://github.com/wso2/integration-studio/issues/778
> Enable http and https protocols by default for dss

- components/esb-tools/plugins/org.wso2.integrationstudio.esb.project/DeployedEndpointsPages/index.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.project/DeployedEndpointsPages/js/store.js
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.project/src/org/wso2/integrationstudio/esb/project/ui/view/DeployedServicesView.java
- components/server-tools/plugins/org.wso2.integrationstudio.carbonserver44microei40/src/org/wso2/integrationstudio/carbonserver44microei40/util/EmbeddedServerManagementAPIUtils.java
> $subject
Fixes: https://github.com/wso2/integration-studio/issues/794
> List resource of an api in runtime services view

- components/dss-tools/plugins/org.wso2.integrationstudio.ds.editor/DSSEditor/index.html
> $subject
Fixes: https://github.com/wso2/integration-studio/issues/779
> Fix auto correction in DSS editor

- components/dss-tools/plugins/org.wso2.integrationstudio.ds.editor/DSSEditor/assets/js/q-output-mapping-validation.js
> $subject
Fixes: https://github.com/wso2/integration-studio/issues/782
> Add default values for DSS output mapping generation

- components/dss-tools/plugins/org.wso2.integrationstudio.ds.editor/DSSEditor/assets/js/ds-validation.js
> Fix: https://github.com/wso2/integration-studio/issues/783
> remove OData option from CSV datasource type

- components/server-tools/plugins/org.wso2.integrationstudio.carbonserver44microei40/resources/server/deployment.toml
- components/studio-platform/plugins/org.wso2.integrationstudio.docker.distribution/resources/deployment.toml
> $subject since default value is there from the PR https://github.com/wso2/micro-integrator/pull/2119
> Remove heartbeat_interval from deployment toml

- components/server-tools/plugins/org.wso2.integrationstudio.carbonserver44microei40/pom.xml
- distribution/rcp-product/org.wso2.integrationstudio.rcp.product/pom.xml
> Update RC1 paths of mi packs

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/plugin.properties
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src/org/wso2/integrationstudio/gmf/esb/provider/DSSMediatorItemProvider.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src/org/wso2/integrationstudio/gmf/esb/provider/DSSoperationPropertyItemProvider.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src/org/wso2/integrationstudio/gmf/esb/provider/DataMapperMediatorItemProvider.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src/org/wso2/integrationstudio/gmf/esb/provider/NamespacedPropertyItemProvider.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb/model/esb.ecore
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb/model/esb.genmodel
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb/src/org/wso2/integrationstudio/gmf/esb/ArtifactType.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb/src/org/wso2/integrationstudio/gmf/esb/EnrichSourceInlineType.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb/src/org/wso2/integrationstudio/gmf/esb/PayloadFactoryMediator.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb/src/org/wso2/integrationstudio/gmf/esb/impl/AbstractDSSOperationImpl.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb/src/org/wso2/integrationstudio/gmf/esb/impl/AbstractNameValueExpressionPropertyImpl.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb/src/org/wso2/integrationstudio/gmf/esb/impl/EsbFactoryImpl.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb/src/org/wso2/integrationstudio/gmf/esb/impl/EsbPackageImpl.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb/src/org/wso2/integrationstudio/gmf/esb/impl/SynapseAPIImpl.java
> Fix issues with ecore model when generating with new items

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/presentation/EEFNameSpacedPropertyEditorDialog.java
$subject
Fix https://github.com/wso2/integration-studio/issues/303
> Fix initial config not setting issue for expression type

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/parts/forms/CallTemplateMediatorPropertiesEditionPartForm.java
Fix NPE in call template mediator when onError is not set.
> Fix NPE in call template mediator when onError is not set.

- components/dss-tools/plugins/org.wso2.integrationstudio.ds.editor/resources/schema/dss_schema.xsd
Fix https://github.com/wso2/integration-studio/issues/828
> Fix structType parameter not persisting issue in dss

- components/studio-platform/plugins/org.wso2.integrationstudio.distribution.project/src/org/wso2/integrationstudio/distribution/project/ui/wizard/DistributionProjectExportWizardPage.java
- components/studio-platform/plugins/org.wso2.integrationstudio.templates.dashboard/src/org/wso2/integrationstudio/templates/dashboard/handlers/DocumentationViewerHandler.java
- components/studio-platform/plugins/org.wso2.integrationstudio.templates.dashboard/src/org/wso2/integrationstudio/templates/dashboard/web/function/server/JSEmbeddedFunctions.java
> Fix: https://github.com/wso2/integration-studio/issues/824
> Fix older project not running in embedded server issue

- components/server-tools/plugins/org.wso2.integrationstudio.carbonserver44microei40/pom.xml
- distribution/rcp-product/org.wso2.integrationstudio.rcp.product/pom.xml
> update mi and mi-dashboard binary download locations

- components/esb-tools/plugins/org.wso2.integrationstudio.visualdatamapper.diagram/src/org/wso2/integrationstudio/datamapper/diagram/custom/util/ScriptGenerationUtil.java
- components/esb-tools/plugins/org.wso2.integrationstudio.visualdatamapper.diagram/src/org/wso2/integrationstudio/datamapper/diagram/tree/generator/SchemaTransformer.java
> Fix: https://github.com/wso2/integration-studio/issues/841
> Fix datamapper json arrays mapping issue

- gh-docs/developer-guide/integration-studio-catalogue.md
$subject. The change is : remove switching to update-<version> branch as we are no longer using that and the new changes should be added to the main branch.
> Update developer guide

- components/dss-tools/plugins/org.wso2.integrationstudio.artifact.dataservice/src/org/wso2/integrationstudio/artifact/dataservice/ui/wizard/DataServiceCreationWizard.java
- components/dss-tools/plugins/org.wso2.integrationstudio.artifact.dataserviceProject/src/org/wso2/integrationstudio/artifact/dataserviceProject/ui/wizard/DataServiceProjectCreationWizard.java
- components/dss-tools/plugins/org.wso2.integrationstudio.artifact.datasourceproject/src/org/wso2/integrationstudio/artifact/datasourceProject/ui/wizard/DataSourceProjectCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.connector/src/org/wso2/integrationstudio/artifact/connector/ui/wizard/ConnectorCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.project/src/org/wso2/integrationstudio/esb/project/ui/wizard/ESBProjectWizard.java
- components/studio-platform/plugins/org.wso2.integrationstudio.general.project/src/org/wso2/integrationstudio/general/project/ui/wizard/GeneralProjectWizard.java
> Remove manual artifact.xml hidden phase in projects

- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/ui/wizard/SynapseAPICreationWizard.java
This is to fix https://github.com/wso2/integration-studio/issues/844
> Fix integration-studio-844: Add API with different version

- components/dss-tools/plugins/org.wso2.integrationstudio.ds.editor/DSSEditor/assets/js/domutils.js
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.mediator/src/org/wso2/integrationstudio/artifact/mediator/ui/wizard/CustomMediatorCreationWizard.java
> Fix dependency issue in mediators and CDATA issues in dss

- components/dss-tools/plugins/org.wso2.integrationstudio.ds.editor/DSSEditor/assets/js/domutils.js
- components/dss-tools/plugins/org.wso2.integrationstudio.ds.editor/DSSEditor/index.html
> update mssql 7.20.0 connector name

- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.mediator/mediator.properties
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.libraries/src/org/wso2/integrationstudio/esb/libraries/utils/LibraryUtils.java
> Add synapse dependency for mediator project

- components/dss-tools/plugins/org.wso2.integrationstudio.ds.editor/DSSEditor/index.html
> Make QUERY_STRING value correct

- components/studio-platform/plugins/org.wso2.integrationstudio.project.extensions/plugin.xml
> Add JSON and YAML templates as registry resources

- components/dss-tools/plugins/org.wso2.integrationstudio.ds.editor/DSSEditor/assets/js/query-util.js
> Replace new line character with space in Data Service SQL

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.persistence/src/org/wso2/integrationstudio/gmf/esb/internal/persistence/PropertyMediatorTransformer.java
> Fix OM element not saving issue with Property mediator

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/custom/EditorUtils.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/part/EsbPaletteFactory.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/part/HideConnectorWizardPage.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/part/HideShowConnectorWizard.java
> Fixing connector hide/show feature issues

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/validator/ProcessSourceView.java
> Fix source validation issue in payload factory

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/parts/forms/PropertyMediatorPropertiesEditionPartForm.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.persistence/src/org/wso2/integrationstudio/gmf/esb/internal/persistence/PropertyMediatorTransformer.java
> Enabled OM text field in property mediator

- components/esb-tools/plugins/org.wso2.integrationstudio.esb.synapse.unit.test/src/org/wso2/integrationstudio/esb/synapse/unit/test/component/DependencyTree.java
> Add support to unit test artifacts in different projects

- components/esb-tools/plugins/org.wso2.integrationstudio.esb.form.editors/schemas/synapseUnitTestValidation.xsd
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.form.editors/src/org/wso2/integrationstudio/esb/form/editors/unittest/SynapseUnitTestFormToSourceTransformer.java
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.form.editors/src/org/wso2/integrationstudio/esb/form/editors/unittest/SynapseUnitTestSourceToFormDeserializer.java
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.form.editors/src/org/wso2/integrationstudio/esb/form/editors/unittest/commons/Constants.java
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.synapse.unit.test/src/org/wso2/integrationstudio/esb/synapse/unit/test/model/TestCase.java
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.synapse.unit.test/src/org/wso2/integrationstudio/esb/synapse/unit/test/utils/ComboItems.java
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.synapse.unit.test/src/org/wso2/integrationstudio/esb/synapse/unit/test/wizard/testcase/TestCaseCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.synapse.unit.test/src/org/wso2/integrationstudio/esb/synapse/unit/test/wizard/testcase/TestCaseDetailPage.java
Adding HTTPS support for unit tests of APIs in Integration Studio
Fixes : https://github.com/wso2/maven-tools/issues/90
> Add HTTPS support for unit tests of APIs

- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.proxyservice/META-INF/MANIFEST.MF
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.proxyservice/src/org/wso2/integrationstudio/artifact/proxyservice/ui/wizard/ProxyServiceProjectCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/META-INF/MANIFEST.MF
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/util/MetadataUtils.java
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.project/src/org/wso2/integrationstudio/esb/project/refactoring/delete/ESBArtifactMetaDataDeleteParticipant.java
- components/studio-platform/plugins/org.wso2.integrationstudio.distribution.project/src/org/wso2/integrationstudio/distribution/project/editor/DistProjectEditorPage.java
- components/studio-platform/plugins/org.wso2.integrationstudio.distribution.project/src/org/wso2/integrationstudio/distribution/project/ui/wizard/DistributionProjectExportWizardPage.java
> $subject
Fixes: https://github.com/wso2/integration-studio/issues/882
> Generate metadata file for proxy services to support service catalog

- distribution/rcp-product/pom.xml
> Refactor yaml editor update p2 url

- pom.xml
> Update pom.xml profiles

- components/studio-platform/plugins/org.wso2.integrationstudio.updater/src/org/wso2/integrationstudio/updater/handler/RunUpdaterRootJob.java
- distribution/rcp-product/org.wso2.integrationstudio.rcp.product/integrationstudio.product
> Update 8.1.0 update location in RCP repository

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.persistence/src/org/wso2/integrationstudio/gmf/esb/internal/persistence/PropertyMediatorTransformer.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb/model/esb.ecore
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb/model/esb.genmodel
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb/src/org/wso2/integrationstudio/gmf/esb/PropertyDataType.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb/src/org/wso2/integrationstudio/gmf/esb/impl/EsbPackageImpl.java
> Fix: https://github.com/wso2/integration-studio/issues/107
> Add JSON data type to property mediator.

- gh-docs/developer-guide/integration-studio-catalogue.md
> Updated integration studio developer guide

- components/esb-tools/plugins/org.wso2.integrationstudio.esb.synapse.unit.test/src/org/wso2/integrationstudio/esb/synapse/unit/test/utils/ComboItems.java
> $subject
Related Issue: https://github.com/wso2/integration-studio/issues/944
> Add OPTIONS, HEAD, PATCH support to API in unit testing

- gh-docs/developer-guide/integration-studio-catalogue.md
> Update integration studio docs with DSS dependency

- components/studio-platform/plugins/org.wso2.integrationstudio.templates.dashboard/WelcomeDashboard/libs/app_new.js
> Fix welcome page loading issue

- components/esb-tools/plugins/org.wso2.integrationstudio.esb.synapse.unit.test/src/org/wso2/integrationstudio/esb/synapse/unit/test/component/DependencyTree.java
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.synapse.unit.test/src/org/wso2/integrationstudio/esb/synapse/unit/test/wizard/runtest/UnitTestConfigurationWizard.java
> Fixing unit test registry path issue

- components/esb-tools/plugins/org.wso2.integrationstudio.esb.synapse.unit.test/src/org/wso2/integrationstudio/esb/synapse/unit/test/wizard/runtest/UnitTestConfigurationWizard.java
> Fixing unit test config reset issue

- components/dss-tools/plugins/org.wso2.integrationstudio.ds.editor/DSSEditor/assets/js/datasources-util.js
- components/dss-tools/plugins/org.wso2.integrationstudio.ds.editor/DSSEditor/assets/js/ds-validation.js
- components/dss-tools/plugins/org.wso2.integrationstudio.ds.editor/DSSEditor/index.html
> Adding ssl support for mongodb configs

- components/dss-tools/plugins/org.wso2.integrationstudio.ds.editor/DSSEditor/assets/js/datasources-util.js
- components/dss-tools/plugins/org.wso2.integrationstudio.ds.editor/DSSEditor/assets/js/ds-validation.js
- components/dss-tools/plugins/org.wso2.integrationstudio.ds.editor/DSSEditor/index.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.synapse.unit.test/src/org/wso2/integrationstudio/esb/synapse/unit/test/component/DependencyTree.java
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.synapse.unit.test/src/org/wso2/integrationstudio/esb/synapse/unit/test/wizard/runtest/UnitTestConfigurationWizard.java
- components/studio-platform/plugins/org.wso2.integrationstudio.templates.dashboard/WelcomeDashboard/libs/app_new.js
> Sync update-8.0.0 branch with main branch 

- components/server-tools/plugins/org.wso2.integrationstudio.carbonserver44microei40/src/org/wso2/integrationstudio/carbonserver44microei40/monitor/CarbonServerListener.java
> Fix : OSGi issue with org.wso2.carbon.capp.monitor-3.0.0.jar by removing unwanted usage
> Remove unused carbon monitor jar usage

- components/studio-platform/plugins/org.wso2.integrationstudio.distribution.project/src/org/wso2/integrationstudio/distribution/project/editor/DistProjectEditorPage.java
$subject
Related to https://github.com/wso2/micro-integrator/issues/2551
> Add support to Conditionally include metadata dependencies

- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/project_wizard.xml
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/exceptions/APIMConnectException.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/exceptions/HttpClientException.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/exceptions/InvalidTokenException.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/model/APIArtifactModel.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/model/APIMAPIArtifactModel.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/model/PublisherAPI.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/ui/wizard/ImportPublisherAPIWizardPage.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/ui/wizard/SynapseAPICreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/util/ArtifactConstants.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/util/HttpClientUtil.java
This is the initial PR for the top-down API development feature.
This include major parts of the integration studio task.
> Top down api development feature initial PR

- components/studio-platform/plugins/org.wso2.integrationstudio.platform.ui/src/org/wso2/integrationstudio/platform/ui/validator/CommonFieldValidator.java
> Allow "." in IntegrationStudio artifact names.
> Updated the regex pattern to allow dots in artifact names.
> Updated the regex pattern to allow dots in artifact names.

- components/studio-platform/plugins/org.wso2.integrationstudio.platform.ui/src/org/wso2/integrationstudio/platform/ui/validator/CommonFieldValidator.java
- distribution/rcp-product/org.wso2.integrationstudio.rcp.product/integrationstudio.product
> Allow "." in IntegrationStudio artifact names.
> Updated the regex pattern to allow dots in artifact names.
> Allow "." in IntegrationStudio artifact names.

- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/project_wizard.xml
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/exceptions/APIMConnectException.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/exceptions/HttpClientException.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/exceptions/InvalidTokenException.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/model/APIArtifactModel.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/model/APIMAPIArtifactModel.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/model/PublisherAPI.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/ui/wizard/ImportPublisherAPIWizardPage.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/ui/wizard/SynapseAPICreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/util/ArtifactConstants.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/util/HttpClientUtil.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/util/MetadataUtils.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/util/constants.properties
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.project/src/org/wso2/integrationstudio/esb/project/artifact/ESBArtifact.java
As $subject, this will add a new option to create API. From this users can login to the API manager and pull the API from API Manager and can start to develop an integration solution.
- https://github.com/wso2/product-apim/issues/11918
- https://github.com/wso2/integration-studio/issues/936
> Add a option to import API Manager API and create integration solution

- distribution/rcp-product/org.wso2.integrationstudio.rcp.product/integrationstudio.product
> Add new update site location  in integration studio. New update site performs customer authentication.
> Add new NGINX update site location

- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/util/ArtifactConstants.java
$Subject
- https://github.com/wso2/product-apim/issues/12375
> Change Publisher REST API version

- pom.xml
> fix typo in the pom file

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.persistence/src/org/wso2/integrationstudio/gmf/esb/internal/persistence/custom/CustomSynapsePathFactory.java
> Fixes : https://github.com/wso2/integration-studio/issues/1025
> Replace all the trailing dots from the path.
> [FIX] Remove trailing dots in synapse path.

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/edit/parts/CallTemplateMediatorEditPart.java
- components/studio-platform/plugins/org.wso2.integrationstudio.project.extensions/resources/templates/endpoint_templates/Address.xml
> Fixes : https://github.com/wso2/integration-studio/issues/1002
Fixes : https://github.com/wso2/integration-studio/issues/1033
> Traverse through all open workspace projects and open the file if it exists.
> [IMPROVEMENT] Open other project's template editor.

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/custom/perspective/EsbGraphicalEditorPerspective.java
- distribution/rcp-product/org.wso2.integrationstudio.rcp.product/integrationstudio.product
> Fixes : https://github.com/wso2/integration-studio/issues/1036
> Removed the feature from the perspective.
> Removed http4e view from perspective.

- distribution/rcp-product/org.wso2.integrationstudio.rcp.product/pom.xml
> update dashboard pom version for 4.1.0-beta

- components/esb-tools/plugins/org.wso2.integrationstudio.esb.synapse.unit.test/src/org/wso2/integrationstudio/esb/synapse/unit/test/wizard/runtest/UnitTestConfigurationWizard.java
> Fix: https://github.com/wso2/integration-studio/issues/1043
> remove unit test maven profile cache

- distribution/rcp-product/org.wso2.integrationstudio.rcp.product/integrationstudio.product
> Fix: https://github.com/wso2/integration-studio/issues/1047
> Change default workspace to 8.1.0/workspace

- components/studio-platform/plugins/org.wso2.integrationstudio.platform.ui/src/org/wso2/integrationstudio/platform/ui/utils/PlatformUIConstants.java
> Fix: https://github.com/wso2/integration-studio/issues/1047#issuecomment-1063855844
> Update docker docker image version to 4.1.0

- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/ContentBasedRouting/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/EmailService/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/ExceptionHandling/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/FetchSalesForceAccounts/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/GuaranteedDelivery/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/HeaderBasedRouting/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/HelloDocker/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/HelloKubernetes/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/HelloWorldService/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/JMSIntegration/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/JSONtoXMLMapping/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/KafkaConsumerandProducer/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/MessageFiltering/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/ProtocolSwitching/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/ProxyingaRESTService/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/ProxyingaSOAPService/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/RESTDataService/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/RESTtoSOAPConversion/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/RabbitMQIntegration/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/ScatterGatherIntegrationPattern/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/StudentsDataService/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/XMLToJSONTransformation/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/XMLtoJSONMapping/Readme.html
> Fixes : https://github.com/wso2/integration-studio/issues/1054
> Removed http client reference from samples guide.

- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/HelloKubernetes/Readme.html
> Fixes : https://github.com/wso2/integration-studio/issues/1062
> Fix k8s-ei-operator Github repository path in Hello Kubernetes sample tamplate's readme

- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/HelloKubernetes/Readme.html
> To support k8s-api-operator in Hello Kubernetes template
> Update Hello Kubernetes template's readme file to support k8s-api-operator

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/resources/schema/mediators/advanced/clone.xsd
Fix clone mediator erroneous synapse code suggestions issue
https://github.com/wso2/integration-studio/issues/1038
> Fix clone mediator erroneous synapse code suggestions issue

- distribution/rcp-product/org.wso2.integrationstudio.rcp.product/pom.xml
> Update dashboard version to 4.1.0-rc1

- components/dss-tools/plugins/org.wso2.integrationstudio.artifact.datasource/DataSourceEditor/assets/js/data-handler.js
- components/dss-tools/plugins/org.wso2.integrationstudio.artifact.datasource/DataSourceEditor/assets/js/datasources-util.js
$subject and fix for https://github.com/wso2/integration-studio/issues/1081
> Fix for DataSource fields not saving issue

- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/ui/wizard/SynapseAPICreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb/src/org/wso2/integrationstudio/gmf/esb/ContentType.java
- pom.xml
> Fix build in mi not working issue

- components/esb-tools/plugins/org.wso2.integrationstudio.esb.form.editors/src/org/wso2/integrationstudio/esb/form/editors/ui/widgets/CompositeElements.java
Fix for https://github.com/wso2/integration-studio/issues/1082
> Add HTTP endpoint additional parameter key, value labels

- distribution/rcp-product/org.wso2.integrationstudio.rcp.product/scripts/lua-nginx-auth-script/lua-auth.lua
Deliver Integration Studio updates only for subscription customers through a NGINX server facilitating customer authentication using a Lua script.
> Add Lua script file (authentication for integration studio updates)

- components/server-tools/plugins/org.wso2.integrationstudio.carbonserver44microei41/serverdefinition/carbon.microIntegrator.definition.xml
$subject
Resolves https://github.com/wso2/integration-studio/issues/1090
> Add system properties to disable warnings in embedded MI

- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/ui/wizard/ImportPublisherAPIWizardPage.java
> fixes : https://github.com/wso2/integration-studio/issues/1092
> UI issue on REST API creation using API Manager API

- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/ui/wizard/ImportPublisherAPIWizardPage.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/ui/wizard/SynapseAPICreationWizard.java
- pom.xml
> Fix: https://github.com/wso2/integration-studio/issues/1089
> fix issues for 8.1.0-rc2 release

- components/dss-tools/plugins/org.wso2.integrationstudio.artifact.datasource/DataSourceEditor/assets/js/data-handler.js
- components/dss-tools/plugins/org.wso2.integrationstudio.artifact.datasource/DataSourceEditor/assets/js/datasources-util.js
Fix for https://github.com/wso2/integration-studio/issues/1095
> Fix DataSource source view not saving

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/debugger/debugpoint/builder/impl/APIDebugPointBuilder.java
Fix for https://github.com/wso2/integration-studio/issues/959
> Fix for mediation debug not working when API version is specified

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/providers/assistants/EsbModelingAssistantProviderOfNTLMMediatorEditPart.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/providers/assistants/EsbModelingAssistantProviderOfNTLMMediatorInputConnectorEditPart.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/providers/assistants/EsbModelingAssistantProviderOfNTLMMediatorOutputConnectorEditPart.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.persistence/src/org/wso2/integrationstudio/gmf/esb/internal/persistence/NTLMMediatorTransformer.java
$subject
https://github.com/wso2/integration-studio/pull/953
> Add WSO2 license header in files for NTLM mediator

- components/esb-tools/plugins/org.wso2.integrationstudio.esb.form.editors/src/org/wso2/integrationstudio/esb/form/editors/unittest/SynapseUnitTestFormToSourceTransformer.java
$subject
Fixes (1) in https://github.com/wso2/integration-studio/issues/1105
> Fix for unit testing assert expression not working

- components/esb-tools/plugins/org.wso2.integrationstudio.visualdatamapper.diagram/src/org/wso2/integrationstudio/datamapper/diagram/custom/action/ExportSchemaAction.java
- components/esb-tools/plugins/org.wso2.integrationstudio.visualdatamapper.diagram/src/org/wso2/integrationstudio/datamapper/diagram/custom/action/Messages.java
- components/esb-tools/plugins/org.wso2.integrationstudio.visualdatamapper.diagram/src/org/wso2/integrationstudio/datamapper/diagram/custom/action/messages.properties
> Add export schema support to Data-mapper mediator
Fixes wso2/api-manager/issues/246
> Add export schema support to DM mediator

- gh-docs/developer-guide/integration-studio-catalogue.md
> Fix typos in the developer guide
> Fix typos in the developer guide

- components/esb-tools/plugins/org.wso2.integrationstudio.visualdatamapper.diagram/build.properties
> Add missing resource file.

- components/esb-tools/plugins/org.wso2.integrationstudio.visualdatamapper.diagram/src/org/wso2/integrationstudio/datamapper/diagram/custom/util/ScriptGenerationUtil.java
> Fixes : https://github.com/wso2-enterprise/wso2-apim-internal/issues/344
> Avoid creating variable name using array default name

- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/HelloKubernetes/Readme.html
> Fix HelloKubernetes template Readme to support API Operator.
> Transition from EI Operator to API operator.
> Fix HelloKubernetes Readme to support API Operator

- components/esb-tools/plugins/org.wso2.integrationstudio.visualdatamapper.diagram/src/org/wso2/integrationstudio/datamapper/diagram/schemagen/util/SchemaBuilder.java
> Fixes : https://github.com/wso2-enterprise/wso2-apim-internal/issues/342
> Add String as default schema when json value is null

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/validator/ProcessSourceView.java
Fixes https://github.com/wso2/api-manager/issues/307
Adding check condition, when there is a fault mediator inside a filter mediator.
> Add specific check condition to filter mediators

- components/esb-tools/plugins/org.wso2.integrationstudio.visualdatamapper.diagram/src/org/wso2/integrationstudio/datamapper/diagram/schemagen/util/SchemaBuilder.java
> Fixes: https://github.com/wso2-enterprise/wso2-apim-internal/issues/342
> Set JSON array type as String even if the last element of the array is an empty string

- components/server-tools/plugins/org.wso2.integrationstudio.carbonserver44microei41/pom.xml
- components/studio-platform/plugins/org.wso2.integrationstudio.registry.resource.authorization/META-INF/MANIFEST.MF
- distribution/rcp-product/org.wso2.integrationstudio.rcp.product/pom.xml
> fix https://github.com/wso2-enterprise/wso2-apim-internal/issues/290
> Fix javax issue while remote CApp deployment

- components/studio-platform/plugins/org.wso2.integrationstudio.kernel.libraries/.classpath
- components/studio-platform/plugins/org.wso2.integrationstudio.kernel.libraries/META-INF/MANIFEST.MF
- components/studio-platform/plugins/org.wso2.integrationstudio.kernel.libraries/build.properties
> fix javax issue with studio remote capp

- components/dss-tools/plugins/org.wso2.integrationstudio.artifact.dataservice/src/org/wso2/integrationstudio/artifact/dataservice/ui/wizard/DataServiceCreationWizard.java
- components/dss-tools/plugins/org.wso2.integrationstudio.artifact.dataservice/src/org/wso2/integrationstudio/artifact/dataservice/ui/wizard/GenerateDataServicesWizardPage.java
Fixes https://github.com/wso2/api-manager/issues/293
> Use datasource name in Dataservices instead of the file name

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/part/EsbMultiPageEditor.java
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/346
Create a new job to update XML files in ESBMultipage editor updateAssociatedXMLFile method to avoid scheduling rule mismatch errors when trying to save .dmc and .xml files at the same time.
> Fix a shceduling rule mismatch issue

- components/dss-tools/plugins/org.wso2.integrationstudio.ds.editor/build.properties
> Remove DB connector lib directory from the build file.
> Remove lib  directory from build file

- components/server-tools/plugins/org.wso2.integrationstudio.carbonserver44microei41/pom.xml
> Fix Jenkins build issue with builtin server

- components/server-tools/plugins/org.wso2.integrationstudio.carbonserver44microei42/pom.xml
- distribution/rcp-product/org.wso2.integrationstudio.rcp.product/pom.xml
> Update MI, MI-dashboard M1 draft URLs

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src/org/wso2/integrationstudio/gmf/esb/provider/CallTemplateParameterItemProvider.java
> Move hardcoded values to constants. Fix spacing.
> Improve code quality 

- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/ContentBasedRouting/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/EmailService/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/ExceptionHandling/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/FetchSalesForceAccounts/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/GuaranteedDelivery/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/HeaderBasedRouting/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/HelloDocker/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/HelloKubernetes/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/HelloWorldService/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/JMSIntegration/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/JSONtoXMLMapping/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/KafkaConsumerandProducer/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/MessageFiltering/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/ProtocolSwitching/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/ProxyingaRESTService/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/ProxyingaSOAPService/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/RESTDataService/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/RESTtoSOAPConversion/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/RabbitMQIntegration/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/ScatterGatherIntegrationPattern/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/StudentsDataService/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/XMLToJSONTransformation/Readme.html
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/NewSamples/XMLtoJSONMapping/Readme.html
> Readme files has "Click the Send" text it should be "Click Send"
> Fix Readme files

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/part/EsbDiagramEditorUtil.java
- gh-docs/developer-guide/integration-studio-catalogue.md
> Remove unnecessary lines. Move hard-coded values to constants.
> Improve code quality

- components/dss-tools/plugins/org.wso2.integrationstudio.artifact.datasource/DataSourceEditor/index.html
Fixes : https://github.com/wso2/api-manager/issues/294
> changing test connection password field type to password

- components/esb-tools/plugins/org.wso2.integrationstudio.visualdatamapper.diagram/src/org/wso2/integrationstudio/datamapper/diagram/xslt/XSLTGenerator.java
- components/esb-tools/plugins/org.wso2.integrationstudio.visualdatamapper.diagram/src/org/wso2/integrationstudio/datamapper/diagram/xslt/config/XSLTGeneratorConstants.java
Fix https://github.com/wso2/api-manager/issues/455
> Update xstl generator

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/presentation/EEFPropertyViewUtil.java
- components/esb-tools/plugins/org.wso2.integrationstudio.visualdatamapper.diagram/src/org/wso2/integrationstudio/datamapper/diagram/schemagen/util/SchemaBuilder.java
> Fix code format

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/presentation/PropertiesWidgetProvider.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/presentation/condition/manager/EnableConditionManager.java
Fix for https://github.com/wso2/api-manager/issues/727
> Fix for connector attributes not getting updated for combo changes

- components/studio-platform/plugins/org.wso2.integrationstudio.distribution.project/plugin.xml
> Fixes: https://github.com/wso2/api-manager/issues/1016
> Add new 4.1.0 and 4.2.0 to plugin.xml

- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/util/ArtifactConstants.java
$subject
Resolves https://github.com/wso2/api-manager/issues/993
Related to https://github.com/wso2/api-manager/issues/958
> Upgrade Publisher api version for 4.2.0

- components/studio-platform/plugins/org.wso2.integrationstudio.distribution.project/plugin.xml
> Fixes: https://github.com/wso2/api-manager/issues/1016
> Add new 4.1.0 and 4.2.0 publishers to plugin.xml

- components/dss-tools/plugins/org.wso2.integrationstudio.ds.editor/DSSEditor/assets/js/q-output-mapping-validation.js
> Fixes: https://github.com/wso2/api-manager/issues/1078
> Change to child nodes if children elements array is empty

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/validator/ProcessSourceView.java
This PR fixes the comment in https://github.com/wso2/integration-studio/pull/1141
> Add null check for next.getqName method

- components/dss-tools/plugins/org.wso2.integrationstudio.artifact.datasource/DataSourceEditor/assets/js/data-handler.js
- components/dss-tools/plugins/org.wso2.integrationstudio.artifact.datasource/DataSourceEditor/assets/js/datasources-util.js
The UI for creating/editing a Datasource in Integration Studio in Windows is not working properly even though the same UI is working fine in Ubuntu and macOS.
This PR fixes the issues in the UI in Windows.
Fixes https://github.com/wso2/api-manager/issues/1157
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
> Fix issues in New Datasource UI in Windows.

- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/src/org/wso2/integrationstudio/esb/dashboard/templates/maven/wizard/CommonTemplateProjectCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/src/org/wso2/integrationstudio/esb/dashboard/templates/maven/wizard/TemplateCreationUtil.java
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.project/src/org/wso2/integrationstudio/esb/project/ui/wizard/ESBProjectWizard.java
$subject
https://github.com/wso2/maven-tools/pull/104
> Update synapse-unit-test-maven-plugin version

- components/studio-platform/plugins/org.wso2.integrationstudio.templates.dashboard/WelcomeDashboard/index.html
This commit will resolve https://github.com/wso2/api-manager/issues/1295
> Remove Unused BPMN Project Creation Options

- components/server-tools/plugins/org.wso2.integrationstudio.carbonserver44microei42/pom.xml
- distribution/rcp-product/org.wso2.integrationstudio.rcp.product/pom.xml
- pom.xml
> prepare for integration studio 8.2.0-beta release

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/custom/deserializer/DataServicesCallMediatorDeserializer.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.persistence/src/org/wso2/integrationstudio/gmf/esb/internal/persistence/DataServiceCallMediatorTransformer.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb/src/org/wso2/integrationstudio/gmf/esb/DSSoperationProperty.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb/src/org/wso2/integrationstudio/gmf/esb/impl/DSSoperationPropertyImpl.java
>  Fixes: https://github.com/wso2/api-manager/issues/1732
> Add support for json expressions in data service call mediator

- components/server-tools/plugins/org.wso2.integrationstudio.carbonserver44microei42/pom.xml
- components/studio-platform/plugins/org.wso2.integrationstudio.kernel.libraries/.classpath
- components/studio-platform/plugins/org.wso2.integrationstudio.kernel.libraries/META-INF/MANIFEST.MF
- components/studio-platform/plugins/org.wso2.integrationstudio.kernel.libraries/build.properties
to fix https://github.com/wso2/api-manager/issues/1769
> Bump SOAP to REST dependency

- components/studio-platform/plugins/org.wso2.integrationstudio.updater/src/org/wso2/integrationstudio/updater/handler/RunUpdaterRootJob.java
- distribution/rcp-product/org.wso2.integrationstudio.rcp.product/integrationstudio.product
> fix issue with update site

- components/studio-platform/plugins/org.wso2.integrationstudio.maven.multi.module/src/org/wso2/integrationstudio/maven/multi/module/editor/DistProjectEditorPage.java
> Add solution profile as initially designed.
Add default profile with a check, so that we can add custom profiles. Fixes github.com/wso2/api-manager/issues/1776
> Fix module auto-removing issues in MMM project

- components/studio-platform/plugins/org.wso2.integrationstudio.kernel.libraries/.classpath
- components/studio-platform/plugins/org.wso2.integrationstudio.kernel.libraries/META-INF/MANIFEST.MF
- components/studio-platform/plugins/org.wso2.integrationstudio.kernel.libraries/build.properties
Update integration studio kernel with the latest soap-to-rest version.
> Update kernel libraries with latest soap-to-rest versions

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/edit/parts/SynapseAPIEditPart.java
> Disable drag option and remove clickable corners in syanspe API. 
Fixes wso2/api-manager/issues/1829
> Disable drag option on synapse API

- components/server-tools/plugins/org.wso2.integrationstudio.carbonserver44microei42/serverdefinition/carbon.microIntegrator.definition.xml
> Fixes: https://github.com/wso2/api-manager/issues/1845
> Add log files arg to server startup

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/part/EsbDiagramEditorUtil.java
Reverts wso2/integration-studio#1216 due to issues with Windows environment
> Revert "Fix diagram view loading issue due to URL encoding in workspace"

- components/esb-tools/plugins/org.wso2.integrationstudio.esb.project/src/org/wso2/integrationstudio/esb/project/model/ESBSolutionProjectModel.java
Fixes https://github.com/wso2/api-manager/issues/1873
> Fix an issue when creating an Integration Project with modified ESB config module name

- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.proxyservice/src/org/wso2/integrationstudio/artifact/proxyservice/ui/wizard/ProxyServiceProjectCreationWizard.java
Fix for https://github.com/wso2-enterprise/wso2-apim-internal/issues/3497
> Add metaplugin entry when creating proxy

- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/ui/wizard/SynapseAPICreationWizard.java
- components/studio-platform/plugins/org.wso2.integrationstudio.kernel.libraries/.classpath
- components/studio-platform/plugins/org.wso2.integrationstudio.kernel.libraries/META-INF/MANIFEST.MF
- components/studio-platform/plugins/org.wso2.integrationstudio.kernel.libraries/build.properties
> Update the soap to rest dependency
Add logic to wrap optional elements with if conditions in freemarker template
> Add optional value support in wsdl to rest feature

- components/studio-platform/plugins/org.wso2.integrationstudio.kernel.libraries/.classpath
- components/studio-platform/plugins/org.wso2.integrationstudio.kernel.libraries/META-INF/MANIFEST.MF
- components/studio-platform/plugins/org.wso2.integrationstudio.kernel.libraries/build.properties
> Upgrade SOAP to REST jar to fix optional value handling in nested complex types
fixes wso2/api-manager/issues/2028
> Fix optional value handling in nested complex types

- components/dss-tools/plugins/org.wso2.integrationstudio.artifact.dataservice/src/org/wso2/integrationstudio/artifact/dataservice/ui/wizard/DataServiceCreationWizard.java
- components/dss-tools/plugins/org.wso2.integrationstudio.artifact.datasource/src/org/wso2/integrationstudio/artifact/datasource/wizards/DataSourceWizard.java
- components/dss-tools/plugins/org.wso2.integrationstudio.artifact.datasourceproject/src/org/wso2/integrationstudio/artifact/datasourceProject/refactor/DataSourceDeleteParticipant.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.connector/src/org/wso2/integrationstudio/artifact/connector/artifact/ConnectorDeleteParticipant.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.connector/src/org/wso2/integrationstudio/artifact/connector/project/nature/ConnectorProjectNature.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.endpoint/src/org/wso2/integrationstudio/artifact/endpoint/ui/wizard/EndpointProjectCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.inboundendpoint/src/org/wso2/integrationstudio/artifact/inboundendpoint/ui/wizard/InboundEndpointProjectCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.localentry/src/org/wso2/integrationstudio/artifact/localentry/ui/wizard/LocalEntryProjectCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.messageprocessor/src/org/wso2/integrationstudio/artifact/messageprocessor/wizard/MessageProcessorCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.messagestore/src/org/wso2/integrationstudio/artifact/messagestore/ui/wizard/MessageStoreCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.proxyservice/src/org/wso2/integrationstudio/artifact/proxyservice/ui/wizard/ProxyServiceProjectCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.sequence/src/org/wso2/integrationstudio/artifact/sequence/ui/wizard/SequenceProjectCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/ui/wizard/SynapseAPICreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.task/src/org/wso2/integrationstudio/artifact/task/ui/wizard/TaskCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.artifact.template.sequence/src/org/wso2/integrationstudio/artifact/template/wizards/TemplateProjectCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.core/src/org/wso2/integrationstudio/esb/core/utils/SynapseUtils.java
Fix: https://github.com/wso2/integration-studio/issues/1239
> Fix backward compatibility issue with projects

- components/esb-tools/plugins/org.wso2.integrationstudio.esb.project/plugin.xml
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.project/src/org/wso2/integrationstudio/esb/project/ui/action/ChangeRuntimeVersion.java
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.project/src/org/wso2/integrationstudio/esb/project/ui/wizard/ESBSolutionProjectCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/custom/deserializer/ClassMediatorExtFactory.java
Fix: https://github.com/wso2/integration-studio/issues/1243
> Fix issue with class mediator craetion

- components/studio-platform/plugins/org.wso2.integrationstudio.docker.distribution/src/org/wso2/integrationstudio/docker/distribution/action/DockerBuildActionUtil.java
- components/studio-platform/plugins/org.wso2.integrationstudio.docker.distribution/src/org/wso2/integrationstudio/docker/distribution/action/DockerRunMavenAction.java
- components/studio-platform/plugins/org.wso2.integrationstudio.docker.distribution/src/org/wso2/integrationstudio/docker/distribution/action/MavenJobThread.java
- components/studio-platform/plugins/org.wso2.integrationstudio.docker.distribution/src/org/wso2/integrationstudio/docker/distribution/editor/CustomWizardDialog.java
- components/studio-platform/plugins/org.wso2.integrationstudio.docker.distribution/src/org/wso2/integrationstudio/docker/distribution/editor/DistProjectEditorPage.java
- components/studio-platform/plugins/org.wso2.integrationstudio.docker.distribution/src/org/wso2/integrationstudio/docker/distribution/editor/DockerHubLoginPage.java
- components/studio-platform/plugins/org.wso2.integrationstudio.docker.distribution/src/org/wso2/integrationstudio/docker/distribution/model/DockerHubAuth.java
- components/studio-platform/plugins/org.wso2.integrationstudio.docker.distribution/src/org/wso2/integrationstudio/docker/distribution/ui/wizard/ContainerProjectCreationWizard.java
> Reformat docker module code

- components/studio-platform/plugins/org.wso2.integrationstudio.kernel.libraries/.classpath
- components/studio-platform/plugins/org.wso2.integrationstudio.kernel.libraries/META-INF/MANIFEST.MF
- components/studio-platform/plugins/org.wso2.integrationstudio.kernel.libraries/build.properties
> Upgrade soap to rest dependency
Related to wso2/integration-studio/issues/1242
> Upgrade soap to rest dependency

- components/dss-tools/plugins/org.wso2.integrationstudio.ds.editor/DSSEditor/assets/js/datasources-util.js
- components/dss-tools/plugins/org.wso2.integrationstudio.ds.editor/DSSEditor/index.html
- components/dss-tools/plugins/org.wso2.integrationstudio.ds.editor/resources/schema/dss_schema.xsd
> Fix for: https://github.com/wso2/integration-studio/issues/1260
> Add property type support for External sources

- components/esb-tools/plugins/org.wso2.integrationstudio.visualdatamapper.diagram/src/org/wso2/integrationstudio/datamapper/diagram/edit/parts/DataMapperRootEditPart.java
> Related issue: https://github.com/wso2/integration-studio/issues/1265
> Fix AI datamapper button not working first time

- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/src/org/wso2/integrationstudio/esb/dashboard/templates/maven/wizard/CommonTemplateProjectCreationWizard.java
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.dashboard.templates/src/org/wso2/integrationstudio/esb/dashboard/templates/maven/wizard/TemplateCreationUtil.java
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.project/src/org/wso2/integrationstudio/esb/project/ui/wizard/ESBProjectWizard.java
This is to upgrade synapse unit maven plugin
Related issue: https://github.com/wso2/integration-studio/issues/1268
> Upgrade synapse-unit-test-maven-plugin version

- distribution/rcp-product/org.wso2.integrationstudio.rcp.product/pom.xml
> This PR Updates the apache-maven download link.
> Update apache-maven download link

- distribution/rcp-product/org.wso2.integrationstudio.rcp.plugin/src/org/wso2/integrationstudio/rcp/plugin/handler/SplashHandler.java
Fix the splash screen flip issue in new Mac versions. 
Fixes: https://github.com/wso2/integration-studio/issues/1257
> Fix the splash screen flip issue in new Mac versions

- components/studio-platform/plugins/org.wso2.integrationstudio.updater/src/org/wso2/integrationstudio/updater/handler/RunUpdaterRootJob.java
Update release notes URL and add User-Agent header to fix 403 error when retrieving release notes
Fixes https://github.com/wso2/micro-integrator/issues/3269
> Update release notes URL and add User-Agent header

- SamplesForVSCode/info.json
> Mark not available samples

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/presentation/ConnectionParameterWizard.java
Fix required parameter missing issue when expressions are used in connector connection wizard
Fixes: https://github.com/wso2/integration-studio/issues/1308
> Fix required parameter missing issue when expressions are used in connector connection wizard

- components/server-tools/plugins/org.wso2.integrationstudio.carbonserver44microei43/resources/server/deployment.toml
Add deployment toml changes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter …
> Add deployment toml changes

- distribution/rcp-product/org.wso2.integrationstudio.rcp.product/pom.xml
Add deleted pom
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus …
> Add deleted pom

- components/server-tools/plugins/org.wso2.integrationstudio.carbonserver44microei43/pom.xml
- distribution/rcp-product/org.wso2.integrationstudio.rcp.product/integrationstudio.product
Comment wso2 update script
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter …
> Comment wso2 update script

- components/server-tools/plugins/org.wso2.integrationstudio.carbonserver44microei43/pom.xml
- components/server-tools/plugins/org.wso2.integrationstudio.carbonserver44microei43/resources/server/microesb.zip
- components/studio-platform/plugins/org.wso2.integrationstudio.platform.ui/src/org/wso2/integrationstudio/platform/ui/utils/PlatformUIConstants.java
Add beta release
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus …
> Add beta release

- components/server-tools/plugins/org.wso2.integrationstudio.carbonserver44microei43/pom.xml
- components/studio-platform/plugins/org.wso2.integrationstudio.platform.ui/src/org/wso2/integrationstudio/platform/ui/utils/PlatformUIConstants.java
- distribution/rcp-product/org.wso2.integrationstudio.rcp.product/pom.xml
- pom.xml
Update 8.3.0 release with MI 4.3.0 configs
> Link(s) to product documentation that addresses the changes of this PR. If no doc …
> Prepare to 8.3.0 release

- SamplesForVSCode/info.json
> Change samples JSON

- SamplesForVSCode/connectors_list.json
This PR will update the download URL of the http inbound endpoint.
> Updating the download URL of the http inbound endpoint

- SamplesForVSCode/connectors_list.json
> Add ISO8583 inbound connector

- SamplesForVSCode/connectors_list.json
> Add SMPP inbound connector

- SamplesForVSCode/connectors_list.json
Fix type on SMPP inbound connector links
> Fix type on SMPP inbound connector links

- SamplesForVSCode/connectors_list.json
> Update connector version of amazonsqs

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/type_bug.md
- .github/ISSUE_TEMPLATE/type_improvement.md
- .github/ISSUE_TEMPLATE/type_new_feature.md
- .github/ISSUE_TEMPLATE/type_task.md
> Add issue template

- components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/part/EsbMultiPageEditor.java
- components/studio-platform/plugins/org.wso2.integrationstudio.distribution.project/src/org/wso2/integrationstudio/distribution/project/ui/wizard/DistributionProjectWizard.java
> Fix API design view not getting updated from swagger changes issue. Remove the additional car goal from maven-car-plugin. Fixes wso2-extensions/archetypes/issues/34
Fixes wso2/integration-studio/issues/1320
> Fix API design view not getting updated issue

- SamplesForVSCode/connectors_list.json
> This PR will add the metadata for following healthcare connectors.
> - epic
> - v2tofhir
> - fhirrepository
> Add metadata for healthcare connector listings

- SamplesForVSCode/connectors_list.json
> Update the file-connector version

- SamplesForVSCode/connectors_list.json
> Add metadata for v2tofhir module

- SamplesForVSCode/connectors_list.json
> Add cdc inbound to connector list

- SamplesForVSCode/connectors_list.json
This PR will update the download URL of the Snowflake connector
> Link(s) to product documentation that addresses the changes …
> Update download_url of Snowflake connector

- .github/workflows/push_ubuntu_build.yml
> $Subject
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …
> Enable codecov step in push workflow

- SamplesForVSCode/connectors_list.json
> Update connectors_list.json with new Kafka connector version

- SamplesForVSCode/connectors_list.json
> Update the new smpp version and download location

- SamplesForVSCode/connectors_list.json
Add Facebook and Google Ads connectors for VSCode
> Add Facebook and Google Ads connectors for VSCode

- SamplesForVSCode/connectors_list.json
Add Kafka and Salesforce inbounds for VSCode
> Add Kafka and Salesforce inbounds for VSCode

- components/esb-tools/plugins/org.wso2.integrationstudio.esb.core/src/org/wso2/integrationstudio/esb/core/utils/SynapseUtils.java
> Skip unit test plugin in build-artifacts pom
fixes wso2/integration-studio/issues/1341
> Skip unit test plugin in build-artifacts pom

- components/studio-platform/plugins/org.wso2.integrationstudio.platform.core/plugin.xml
- components/studio-platform/plugins/org.wso2.integrationstudio.platform.core/src/org/wso2/integrationstudio/platform/core/internal/impl/mediatypes/FreeMarkerMediaTypeResolver.java
- components/studio-platform/plugins/org.wso2.integrationstudio.project.extensions/plugin.xml
Add FreeMarker template as a registry resource
> Add FreeMarker template as a registry resource

- SamplesForVSCode/connectors_list.json
> Update FHIR Repository connector version

- components/esb-tools/plugins/org.wso2.integrationstudio.esb.synapse.unit.test/src/org/wso2/integrationstudio/esb/synapse/unit/test/component/DependencyTree.java
- components/esb-tools/plugins/org.wso2.integrationstudio.esb.synapse.unit.test/src/org/wso2/integrationstudio/esb/synapse/unit/test/constant/Constants.java
> Add functionality to include registry properties in synapse unit tests. 
Fixes wso2/micro-integrator/issues/3606
> Add registry properties support to unit tests

- SamplesForVSCode/connectors_list.json
> Update connectors_list.json with new google ads release

- pom.xml
> Change http repository urls to https
> Change http repository urls to https

- SamplesForVSCode/connectors_list.json
> Update connectors_list.json with new googleads and facebookads apis

- SamplesForVSCode/connectors_list.json
> Update connectors_list.json with new amazonsqs connector release

- SamplesForVSCode/connectors_list.json
> Update connector list

- SamplesForVSCode/connectors_list.json
This PR will update the version of the Epic connector.
> Update version of the Epic connector

- SamplesForVSCode/inbound_connector_list.json
> Update inbound_connector_list.json for Kafka inbound endpoint

- SamplesForVSCode/connectors_list.json
> Update connectors_list.json for kafka inbound endpoint

- SamplesForVSCode/connectors_list.json
> Update the mongodb version in connectors_list.json

- SamplesForVSCode/inbound_connector_list.json
Fixes: https://github.com/wso2/mi-vscode/issues/541
> Update inbound connector list descriptions

- SamplesForVSCode/connectors_list.json
$subject
Fixes: https://github.com/wso2/mi-vscode/issues/541
> Update inbound endpoint descriptions for VS Code

- SamplesForVSCode/connectors_list.json
> Update file connector version to v4.0.34

- SamplesForVSCode/connectors_list.json
> Update Kafka connector version to v3.3.4

- SamplesForVSCode/connectors_list.json
> Update CDC inbound EP version

- components/server-tools/plugins/org.wso2.integrationstudio.carbonserver44microei44/pom.xml
> Add MI release URL

- SamplesForVSCode/connectors_list.json
> Update Kafka connector download URL

- SamplesForVSCode/connectors_list.json
> Update Kafka connector version

- SamplesForVSCode/connectors_list.json
> Update file connector version to v4.0.35

- SamplesForVSCode/connectors_list.json
> Update CSV connector version

- SamplesForVSCode/connectors_list.json
> Update snowflake connector version
