components/esb-tools/plugins/org.wso2.integrationstudio.artifact.proxyservice/src/org/wso2/integrationstudio/artifact/proxyservice/model/ProxyServiceModel.java
Currently, URL validator does not accept localhost as a proper valid URL.
Resolves wso2/devstudio-tooling-ei#1317
=> Change Proxy WSDL URL validator to allow localhost

components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/project_wizard.xml, components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/ui/wizard/SynapseAPICreationWizard.java, components/esb-tools/plugins/org.wso2.integrationstudio.artifact.synapse.api/src/org/wso2/integrationstudio/artifact/synapse/api/validator/ProjectFieldController.java, components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/part/EsbMultiPageEditor.java
> $subject
- Add registry path for generating API from a swagger wizard
- Persists swagger sources when saving from the design or source views
=> Refactor API creation from swagger definition path

components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/presentation/EEFNameSpacedPropertyEditorDialog.java
Making the expression dialog box open the JSON path mode when the current expression is a JSON path.
Fix: https://github.com/wso2/integration-studio/issues/490
=> Expression dialog box JSON path default config

components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.persistence/src/org/wso2/integrationstudio/gmf/esb/internal/persistence/HTTPEndPointTransformer.java
Fix double encoding a URL in HTTP Endpoint when an already encoded URL is given.
Fix https://github.com/wso2/integration-studio/issues/265
=> Fix encode issue in Uri template in HTTP Endpoint 

gh-docs/developer-guide/integration-studio-catalogue.md
> When building the project using Maven 3.8.1 or higher, the default HTTP blocker fails the build. Updated the developer guide with the setup guide specifically for those who use maven 3.8.1 or higher.
=> Updated developer guide document with required dev setup information for Maven version 3.8.1 or higher

distribution/rcp-product/org.wso2.integrationstudio.rcp.product/integrationstudio.product
> HTTP4e plugin causes Integration Studio Crashing #956. The purpose is to remove the feature from the IntegrationStudio and update the documentation to guide the customer to use Postman
> Documentation changes: https://github.com/wso2/docs-apim/pull/5192
> Linux, Mac
=> Removed HTTP4E feature from product.

gh-docs/developer-guide/integration-studio-catalogue.md
> Update the developer guide to reflect Java 11 migration and Eclipse 2021-12 migration
=> Update developer guide to reflect 2021-12 eclipse migration.

components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/custom/deserializer/SequenceTemplateDeserializer.java
In TemplateMediator when we change the view from source -> design -> source the "isMendatory" value is restored to false.
Found a bug in the source code which overwrites the value of "isMendatory" with an empty template's value. Fixed that bug.
=> [Fix] Persist the isMendatory value in TemplateMediator

components/studio-platform/plugins/org.wso2.integrationstudio.dashboard/src/org/wso2/integrationstudio/dashboard/handlers/PlatformEarlyStartUpHandler.java
> When migrating to JDK 11, some wrong imports were added. In this commit, those changes are reverted.
=> [Fix] Reverted wrong imports.

components/esb-tools/plugins/org.wso2.integrationstudio.artifact.inboundendpoint/src/org/wso2/integrationstudio/artifact/inboundendpoint/ui/wizard/InboundEndpointProjectCreationWizard.java
> As per the [doc](https://apim.docs.wso2.com/en/latest/reference/connectors/kafka-connector/kafka-inbound-endpoint-example/#kafka-inbound-endpoint-example) default class name for custom inbound endpoint is : org.wso2.carbon.inbound.kafka.KafkaMessageConsumer. Need to change the default value according to the document.
> Updated the code to use  "org.wso2.carbon.inbound.kafka.KafkaMessageConsumer" as default value for custom inbound endpoint class name.
=> Add class name in custom inbound endpoint

components/studio-platform/plugins/org.wso2.integrationstudio.carbon.server.model/src/org/wso2/integrationstudio/carbon/server/model/configuration/ConfigurationOtherCommonEditorSection.java
> Fix issue: Integration studio freezes when opening server configuration screen. 
> In the ConfigurationOtherCommonEditorSection class, there is a never-ending while loop running when going to the config overview UI. Fixed this problem. 
[1](https://github.com/wso2/integration-studio/issues/969)
=> [Fix] Integration Studio crashes on server config screen

gh-docs/developer-guide/integration-studio-catalogue.md
Because we have long file name in our projects, git checkout it failing in windows saying "Filename too long error: unable to create file". Updated the document to address this issue.
=> Git checkout error on windows

components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src/org/wso2/integrationstudio/gmf/esb/provider/CallTemplateParameterItemProvider.java
> In the Windows environment CallTemplate mediator's property section shows name and value without spaces between them. The reason for this issue is Windows ignore '\t' when displaying the text in Table. 
> Programatically determine the OS, If OS is Windows then add "  -  " between name and value.
=> Add space between name and value.

components/dss-tools/plugins/org.wso2.integrationstudio.ds.editor/DSSEditor/assets/js/data-handler.js
> to fix [issue 1](https://github.com/wso2/integration-studio/issues/1008) [issue 2](https://github.com/wso2/integration-studio/issues/1009)
> Reason for this issue is Jquery update. With newer versions of Jquery to use ajax with CORS support, we need to add "jQuery.support.cors = true;" explicitly. Reference : [Stackoverflow thread](https://stackoverflow.com/questions/5241088/jquery-call-to-webservice-returns-no-transport-error)
=> [Fix] Unable to save data service

gh-docs/developer-guide/integration-studio-catalogue.md
> Update the documentation to guide the developer to setup eclipse for IntegrationStudio java 11 development.
=> Updated doc for java 11 IDE setup

components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/part/EsbDiagramEditorUtil.java
> Fixes : [Issue 968](https://github.com/wso2/integration-studio/issues/968)
> In Integration studio EsbDiagramEditoru7til.java file we are trying to save esb files in a relative path (resources/). This approach makes the integration studio create files in the installation folder. When Integration Studio is installed in program files this will give the user permission error. With this code change, integration studio will save the esb files to the current workspace.
=> [FIX] Error while saving a proxy service in Dev studio due to lack of permissions to resources directory

components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb/src/org/wso2/integrationstudio/gmf/esb/impl/PropertyMediatorImpl.java
> Fixes : [Issue 978](https://github.com/wso2/integration-studio/issues/978)
> Changed the mapped value to AXIS2
=> [FIX] Property Scope doesn't change to axis2 when selecting Property Name as REST_URL_POSTFIX

components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/components/CallTemplateMediatorPropertiesEditionComponent.java, components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/presentation/EEFPropertyViewUtil.java, components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb/src/org/wso2/integrationstudio/gmf/esb/impl/CallTemplateParameterImpl.java, components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb/src/org/wso2/integrationstudio/gmf/esb/impl/NamespacedPropertyImpl.java
> Automatically add parameters to the CasllTemplateMediator param section, when the user selects the template.
> Behavior of the change: Let's say we have two Sequence mediators created as follows,
1. Name of mediator A,  Parameters : (A-param1, A-param-2)
2. Name of mediator B,  Parameters : (B-param1, B-param-2)
3. Name od mediator C,  Parameters : (A-param1, B-param1)
Now User creates a CallMediator 
* User will have an empty parameter list in the property section.
* User select template: A in the available templates section of the CallTemplateMediator property section.
* Parameters : (A-param1, A-param-2) will be automatically added to the param table. 
* User select template: B in the available templates section of the CallTemplateMediator property section.
* Parameters : (B-param1, …
=> Auto add params when selecting template.

components/esb-tools/plugins/org.wso2.integrationstudio.esb.synapse.unit.test/src/org/wso2/integrationstudio/esb/synapse/unit/test/component/DependencyTree.java
> Fixes : https://github.com/wso2/integration-studio/issues/1006
> The reason these artifacts and services are not being marked is when comparing the strings, the target string contains "/"s, and source strings contain "\"s. As a fix, removed the slashes from the string before comparing.
=> [FIX] Supportive artifacts are not being marked

components/esb-tools/plugins/org.wso2.integrationstudio.artifact.mediator/src/org/wso2/integrationstudio/artifact/mediator/ui/wizard/CustomMediatorCreationWizard.java
> Fixes : https://github.com/wso2/integration-studio/issues/857
> Root cause : When creating pom file capp.type was not added to the pom file. Fix : Changed the code to add capp.type information to the pom correctly.
=> Class Mediator does not work out of the box

components/esb-tools/plugins/org.wso2.integrationstudio.visualdatamapper.diagram/src/org/wso2/integrationstudio/datamapper/diagram/part/DataMapperDiagramEditor.java
Fixes https://github.com/wso2/api-manager/issues/594
Previously regardless of the Input and Output type, the XSLT sheet was updated in the data mapper, Ideally we should only use XSLT for XML to XML mapping.
=> Update XSLT in datamapper only if input and output type is XML

components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/part/EsbDiagramActionBarContributor.java
The action handlers were overridden to support shortcut keys in the source view. As a result, the Form view will use these overridden action handlers when a source view is opened in the background. To fix this we need to clear the action handlers when the active page is changed to Design or Form view.
Fixes https://github.com/wso2/api-manager/issues/645
=> Fix shortcut issue in form view

components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/custom/deserializer/HTTPEndpointDeserializer.java, components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb/src/org/wso2/integrationstudio/gmf/esb/HTTPEndpointOAuthAuthenticationMode.java
Make the `authMode` parameter optional and set the default value to 'header' in HTTP endpoints.
Fixes https://github.com/wso2/api-manager/issues/720
=> Make authmode optional and set the default value to 'header'

components/esb-tools/plugins/org.wso2.integrationstudio.visualdatamapper.diagram/src/org/wso2/integrationstudio/datamapper/diagram/custom/util/ScriptGenerationUtil.java
The same code block was executed regardless of the conditions `getArrayElementCount(variable.getName(), map) == 1)` in `getPrettyVariableNameInForOperation` method of the DataMapper script generation. This PR removes the redundant if else condition in the data mapper.
Since the condition `getArrayElementCount(variable.getName(), map) == 1)` was removed, the underscore('__') issue related to nested arrays will be fixed.
Fixes https://github.com/wso2/api-manager/issues/708
=> Remove redundant if else condition in datamapper

components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/parts/forms/DSSMediatorPropertiesEditionPartForm.java, components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.edit/src-gen/org/wso2/integrationstudio/gmf/esb/parts/forms/StoreMediatorPropertiesEditionPartForm.java
When one integration project is closed, when we add a DSS Call meditator or a Store mediator to another opened project, it will show an error dialog. To fix this when iterating the project list, we need to have a check to verify the project is open.
Fixes : https://github.com/wso2/api-manager/issues/738
=> Add check to verify the project is open

components/esb-tools/plugins/org.wso2.integrationstudio.artifact.proxyservice/src/org/wso2/integrationstudio/artifact/proxyservice/ui/wizard/ProxyServiceProjectCreationWizard.java
Append .metadata to the maven groupId instead of proxy-service groupId when creating metadata artifacts
Fixes: https://github.com/wso2/api-manager/issues/1321
=> Update metadataGroupId for proxy-service artifacts

components/esb-tools/plugins/org.wso2.integrationstudio.artifact.proxyservice/src/org/wso2/integrationstudio/artifact/proxyservice/ui/wizard/ProxyServiceProjectCreationWizard.java
Append .metadata to the maven groupId instead of proxy-service groupId when creating metadata artifacts.
Fixes: https://github.com/wso2/api-manager/issues/1321
=> [8.1.0] Update metadataGroupId for proxy-service artifacts

components/esb-tools/plugins/org.wso2.integrationstudio.visualdatamapper.diagram/src/org/wso2/integrationstudio/datamapper/diagram/schemagen/util/JsonReferenceResolver.java, components/esb-tools/plugins/org.wso2.integrationstudio.visualdatamapper.diagram/src/org/wso2/integrationstudio/datamapper/diagram/schemagen/util/SchemaGeneratorForJSON.java
Absolute and relative $ref definition paths support added
Fix for https://github.com/wso2/api-manager/issues/147
Now, when importing an input/output file json schema to the datamapper, the references (absolute and relative definitions within the file) will be resolved, and saved in integration studio project.
=> Add json $ref support for datamapper

components/studio-platform/plugins/org.wso2.integrationstudio.platform.ui/src/org/wso2/integrationstudio/platform/ui/wizard/pages/KubernetesDetailsPage.java
This will add a scroll bar to the Kubernetes details page on the integration project creation wizard.
Fix https://github.com/wso2/api-manager/issues/1486
=> Add scroll bar to Kubernetes details page

distribution/rcp-product/org.wso2.integrationstudio.rcp.product/assembly/macosx.cocoa_aarch64.xml, distribution/rcp-product/org.wso2.integrationstudio.rcp.product/pom.xml, distribution/rcp-product/org.wso2.integrationstudio.rcp.product/scripts/package-installer-script.sh, distribution/rcp-product/pom.xml
Add aarch64 build for Integration Studio. This will generate an Integration Studio app that runs natively on apple processors(arm based)
Related issue: https://github.com/wso2/api-manager/issues/1480
=> Add macOS aarch64(Apple silicon) distribution for Integration Studio

components/dss-tools/plugins/org.wso2.integrationstudio.artifact.dataservice/src/org/wso2/integrationstudio/artifact/dataservice/model/DataServiceModel.java, components/dss-tools/plugins/org.wso2.integrationstudio.artifact.dataservice/src/org/wso2/integrationstudio/artifact/dataservice/ui/wizard/GenerateDataServicesWizardPage.java, components/dss-tools/plugins/org.wso2.integrationstudio.artifact.datasource/DataSourceEditor/assets/js/data-handler.js, components/dss-tools/plugins/org.wso2.integrationstudio.artifact.datasource/DataSourceEditor/assets/js/datasources-util.js
This PR contains the fixes for the following issues,
1. Fix issues in New Datasource UI in Windows
Port the fix https://github.com/wso2/integration-studio/pull/1182 to the master branch
Fixes: https://github.com/wso2/api-manager/issues/1588
2. Remove the existing JDBC driver option when fetching tables in the dataservice wizard
Since we have removed the JDBC drivers packed within the Integration Studio with #1157
we need to remove the `Use an existing driver` option when fetching tables in the dataservice wizard
Fixes: https://github.com/wso2/api-manager/issues/1587
3. Fix datasource design view not getting saved
In the current implementation, an `onChange` listener was used in the design view which gets triggered when we click the form
Therefore, add an `onKeyUp` listener with a timeout …
=> Fix issues related to Datasource and DSS views

components/esb-tools/plugins/org.wso2.integrationstudio.esb.project/project_wizard_esb_solution.xml, components/esb-tools/plugins/org.wso2.integrationstudio.esb.project/src/org/wso2/integrationstudio/esb/project/controller/ESBSolutionProjectFieldController.java, components/esb-tools/plugins/org.wso2.integrationstudio.esb.project/src/org/wso2/integrationstudio/esb/project/model/ESBSolutionProjectModel.java, components/esb-tools/plugins/org.wso2.integrationstudio.esb.project/src/org/wso2/integrationstudio/esb/project/ui/wizard/ESBSolutionProjectCreationWizard.java, components/esb-tools/plugins/org.wso2.integrationstudio.esb.project/src/org/wso2/integrationstudio/esb/project/utils/SolutionProjectArtifactConstants.java, components/esb-tools/plugins/org.wso2.integrationstudio.esb.project/src/org/wso2/integrationstudio/esb/project/utils/constants.properties, components/studio-platform/plugins/org.wso2.integrationstudio.platform.ui/src/org/wso2/integrationstudio/platform/ui/utils/PlatformUIConstants.java
Add option to define runtime version for projects in the 'New Integration Project' Wizard
Fixes https://github.com/wso2/api-manager/issues/1841
The developer will have the option to define the runtime version when creating an Integration Project. By default, the version of the MI runtime shipped with the Studio will be set as the project’s runtime version.
=> Add option to define runtime version for projects

components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/part/EsbDiagramEditorUtil.java
IndexOutofBound error gets thrown from the IS if the workspace file path contains a space. This issue was due to the usage of `URI.createURI()` method to generate a file URI object. Having spaces, throw following exception and do not initialize design page data. Since design data page do not available, it throw IndexOutofBound exception.
```
org.eclipse.gmf.runtime.emf.core.util.Util.denormalizeURI(Util.java:164), 
org.eclipse.gmf.runtime.emf.core.resources.GMFResource.setURI(GMFResource.java:112), 
org.eclipse.gmf.runtime.emf.core.internal.resources.PathmapManager.denormalize(PathmapManager.java:819), org.eclipse.gmf.runtime.emf.core.internal.resources.PathmapManager.notifyChanged(PathmapManager.java:584), 
org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.jav …
```
=> Fix diagram view loading issue due to URL encoding in workspace

components/esb-tools/plugins/org.wso2.integrationstudio.gmf.esb.diagram/src/org/wso2/integrationstudio/gmf/esb/diagram/part/EsbDiagramEditorUtil.java
IndexOutofBound error gets thrown from the IS if the workspace file path contains a space. This issue was due to the usage of `URI.createURI()` method to generate a file URI object. Having spaces, throw following exception and do not initialize design page data. Since design data page do not available, it throw IndexOutofBound exception.
```
org.eclipse.gmf.runtime.emf.core.util.Util.denormalizeURI(Util.java:164), 
org.eclipse.gmf.runtime.emf.core.resources.GMFResource.setURI(GMFResource.java:112), 
org.eclipse.gmf.runtime.emf.core.internal.resources.PathmapManager.denormalize(PathmapManager.java:819), org.eclipse.gmf.runtime.emf.core.internal.resources.PathmapManager.notifyChanged(PathmapManager.java:584), 
org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.jav …
```
=> Fix workspace with space character issue

components/studio-platform/plugins/org.wso2.integrationstudio.kernel.libraries/.classpath, components/studio-platform/plugins/org.wso2.integrationstudio.kernel.libraries/META-INF/MANIFEST.MF, components/studio-platform/plugins/org.wso2.integrationstudio.kernel.libraries/build.properties
Update soap-to-rest dependency to version 1.3
https://github.com/wso2/soap-to-rest/pull/8
=> Update soap-to-rest dependency to version 1.3

components/studio-platform/plugins/org.wso2.integrationstudio.maven.multi.module/src/org/wso2/integrationstudio/maven/multi/module/editor/DistProjectEditorPage.java
When a new artifact is added or deleted from the Integration Studio, root pom.xml is always marked with a start which represents it contains modifications. But, removing or adding artifacts actually does not do any modification to the root pom file. Therefore, adding or removing artifacts should not do any modification to the root pom file.
In the current implementation, we always update the version, id, description, and group id every time if there are artifact addition or deletion. Save content only if there are changes. Otherwise, ignore it.
=> Save content only if it changed

components/dss-tools/plugins/org.wso2.integrationstudio.ds.editor/resources/schema/dss_schema.xsd
The valid types for query params are IN, OUT, INOUT. But, the current dss-schema has INOUT as IN-OUT. This pr fixes that issue.
=> Fix DSS schema issue

components/dss-tools/plugins/org.wso2.integrationstudio.ds.editor/DSSEditor/index.html
The form view displays the type as "INOUT". But, it is saved as "IN-OUT" in the source view. This PR fixes this inconsistency.
=> Fix inconsistent value in design and source views for field 'type' in dataservices's queries

components/esb-tools/plugins/org.wso2.integrationstudio.artifact.inboundendpoint/src/org/wso2/integrationstudio/artifact/inboundendpoint/ui/wizard/InboundEndpointProjectCreationWizard.java
Reverts wso2/integration-studio#1010
No need to add Kafka values by default.
=> Revert "Add class name in custom inbound endpoint"

components/dss-tools/plugins/org.wso2.integrationstudio.ds.editor/DSSEditor/assets/js/data-handler.js, components/dss-tools/plugins/org.wso2.integrationstudio.ds.editor/resources/schema/dss_schema.xsd
This PR will update the UI validation and XSD schema for DSS query ID, operation name and datasource name to allow `_` character.
Fixes https://github.com/wso2/micro-integrator/issues/3071
=> Add validation for DSS query ID, operation name and datasource name

components/esb-tools/plugins/org.wso2.integrationstudio.visualdatamapper.diagram/src/org/wso2/integrationstudio/datamapper/diagram/xslt/XSLTGenerator.java
When a default namespace is used in the input, the output mapping is not working as the default namespace was not set in the XSLT generated by the DataMapper. This PR will add `xpath-default-namespace` to the XSLT.
Fixes: https://github.com/wso2/micro-integrator/issues/3328
=> Add default namespace for DataMapper XSLT

gh-docs/developer-guide/apple_sign.sh, gh-docs/developer-guide/entitlements.plist, gh-docs/developer-guide/integration-studio-catalogue.md
=> Update README with notarization process.

SamplesForVSCode/connectors_list.json
=> Add metadata for FHIR connector listing

components/dss-tools/plugins/org.wso2.integrationstudio.ds.editor/DSSEditor/assets/js/data-handler.js
When there are multiple input mapping in a DSS query, the resource edit button is not working as we keep iterating the query list. To fix this we need to break the for loop in DSS queries list when populating the resource table.
=> Break the for loop in DSS queries list when populating the resource table

SamplesForVSCode/connectors_list.json
=> Add Sharepoint connector
